name: Manifest Tests
on:
  pull_request:
    paths:
      - 'templates/**'
      - 'jobs/**'
      - 'packages/**'

concurrency:
  group: "${{ github.workflow }}/${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test_manifest:
    name: Manifest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: .github/actions/setup-environment
        with:
          ssh-key: ${{ secrets.BBL_SSH_KEY }}

      - name: Run Tests - old manifest
        run: |
          set -e

          pushd templates
            MANIFEST_PATH=$PWD/../templates/app-autoscaler-deployment.yml \
            OPERATION_DIR_PATH=$PWD/../example/operation \
            SCALINGENGINE_INSTANCE_GROUP=asactors\
            SCHEDULER_INSTANCE_GROUP=asactors\
            METICSFORWARDER_INSTANCE_GROUP=asapi\
            OPERATOR_INSTANCE_GROUP=asactors\
            EVENTGENERATOR_INSTANCE_GROUP=asmetrics\
            METIRCSSERVER_INSTANCE_GROUP=asmetrics\
            METRICSGATEWAY_INSTANCE_GROUP=asnozzle \
            ./manifest_tests.sh
          popd

      - name: Run Tests - Manifest
        run: |
          set -e

          pushd templates
            MANIFEST_PATH=$PWD/app-autoscaler.yml \
            OPERATION_DIR_PATH=$PWD/../operations \
            ./manifest_tests.sh
          popd
