# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
---
linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
        deny:
          - pkg: github.com/alecthomas/assert
            desc: "use github.com/stretchr/testify/assert"
          - pkg: github.com/magiconair/properties/assert
            desc: "use github.com/stretchr/testify/assert"
          - pkg: code.cloudfoundry.org/cfhttp/handlers
            desc: "use code.cloudfoundry.org/app-autoscaler/src/autoscaler/helpers/handlers"
          - pkg: code.cloudfoundry.org/cfhttp
            desc: "use code.cloudfoundry.org/cfhttp/v2 or code.cloudfoundry.org/tlsconfig"
          - pkg: github.com/lib/pq
            desc: "use github.com/jackc/pgx"
          - pkg: gopkg.in/yaml.v2
            desc: "use gopkg.in/yaml.v3"
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: false
  funlen:
    lines: 250
    statements: 150
  goconst:
    min-len: 3
    min-occurrences: 3
  gocognit:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 30
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks:
          - argument
          - case
          - condition
          - return
  govet:
    enable-all: true
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  staticcheck:
    checks: ["all"]
  stylecheck:
    go: "1.20"
    # https://staticcheck.io/docs/options#checks
    checks: ["all", "-ST1003", "-ST1005"]
    dot-import-whitelist:
      - github.com/onsi/ginkgo/v2
      - github.com/onsi/gomega
      - github.com/onsi/gomega/gexec
    # https://staticcheck.io/docs/options#initialisms
    #initialisms: ["ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS"]
    # https://staticcheck.io/docs/options#http_status_code_whitelist
    #http-status-code-whitelist: ["200", "400", "404", "500"]
linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
      #- dupl
    - errcheck
    - funlen
      #    - gocognit
      #    - goconst
      #    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - gomoddirectives
    - gomodguard
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - testpackage
    - typecheck
      #    - unconvert
      #    - unparam
    - unused
    - whitespace
      #    - godox
      #    - staticcheck
      #    - prealloc
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gomnd
        - typecheck
  max-same-issues: 0
run:
  go: '1.19'
