---

name: app-autoscaler

# Release Details
releases:
- name: app-autoscaler
  version: latest
- name: postgres
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=17
  version: '17'
  sha1: b062e32a5409ccd4e4161337c48705c793a58412
- name: consul
  version: latest

# Stemcell details
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

# Canary details
update:
  canaries: 1
  canary_watch_time: 1000-300000
  max_in_flight: 3
  update_watch_time: 1000-300000

# Instance Group details
instance_groups:
  # Postgres Instance Group
- name: postgres_autoscaler
  azs:
  - z1
  instances: 1
  update:
    serial: true
  stemcell: default
  vm_type: default
  networks:
  - name: default
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul_common: {from: consul_common_link, deployment: cf}
      consul_server: nil
      consul_client: {from: consul_client_link, deployment: cf}
    properties:
      consul:
        agent:
          services:
            postgres:
              check:
                tcp: 127.0.0.1:5432
                interval: 30s
                timeout: 10s
  - name: postgres
    release: postgres
    properties:
      databases: &database
        databases:
        - name: autoscaler
          tag: default
        db_scheme: postgres
        port: 5432
        roles:
        - name: postgres
          password: "((database_password))"
          tag: default

# APIServer Instance Group
- name: apiserver
  azs:
  - z1
  instances: 1
  networks:
  - name: default
  stemcell: default
  vm_type: default
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul_common: {from: consul_common_link, deployment: cf}
      consul_server: nil
      consul_client: {from: consul_client_link, deployment: cf}
    properties:
      consul:
        agent:
          services:
            apiserver: {}
  - name: apiserver
    release: app-autoscaler
    properties:
      api_server:
        db_config: &db_config
          idle_timeout: 1000
          max_connections: 10
          min_connections: 0
        port: 6100
        ca_cert: ((apiserver_ca.ca))
        server_cert: ((apiserver_server.certificate))
        server_key:  ((apiserver_server.private_key))
        scheduler:
          ca_cert: ((scheduler_ca.ca))
          client_cert: ((scheduler_client.certificate))
          client_key: ((scheduler_client.private_key))
        scaling_engine:
          ca_cert: ((scalingengine_ca.ca))
          client_cert: ((scalingengine_client.certificate))
          client_key: ((scalingengine_client.private_key))
        metrics_collector:
          ca_cert: ((metricscollector_ca.ca))
          client_cert: ((metricscollector_client.certificate))
          client_key: ((metricscollector_client.private_key))
      policy_db: *database
      
# Scheduler Instance Group
- name: scheduler
  azs:
  - z1
  instances: 1
  networks:
  - name: default
  stemcell: default
  vm_type: default
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul_common: {from: consul_common_link, deployment: cf}
      consul_server: nil
      consul_client: {from: consul_client_link, deployment: cf}
  - name: scheduler
    release: app-autoscaler
    properties:
      scheduler:
        port: 6102
        job_reschedule_interval_millisecond: 10000
        job_reschedule_maxcount: 6
        notification_reschedule_maxcount: 3
        ca_cert: ((scheduler_ca.ca))
        server_cert: ((scheduler_server.certificate))
        server_key: ((scheduler_server.private_key))
        scaling_engine:
          ca_cert: ((scalingengine_ca.ca))
          client_cert: ((scalingengine_client.certificate))
          client_key: ((scalingengine_client.private_key))
      scheduler_db: *database
      policy_db: *database
      
# Service-Broker Instance Group
- name: servicebroker
  azs:
  - z1
  instances: 1
  networks:
  - name: default
  stemcell: default
  vm_type: default
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul_common: {from: consul_common_link, deployment: cf}
      consul_server: nil
      consul_client: {from: consul_client_link, deployment: cf}
    properties:
      consul:
        agent:
          services:
            servicebroker: {}
  - name: servicebroker
    release: app-autoscaler
    properties:
      service_broker:
        db_config: *db_config
        port : 6101
        ca_cert: ((servicebroker_ca.ca))
        server_cert: ((servicebroker_server.certificate))
        server_key: ((servicebroker_server.private_key))
        username: username
        password: password
        http_request_timeout: 5000
        catalog: 
          services:
          - id: autoscaler-guid
            name: autoscaler
            description: Automatically increase or decrease the number of application instances based on a policy you define.
            bindable: true
            plans:
            - id: autoscaler-free-plan-id
              name: autoscaler-free-plan
              description: This is the free service plan for the Auto-Scaling service.
        api_server:
          ca_cert: ((apiserver_ca.ca))
          client_cert: ((apiserver_client.certificate))
          client_key: ((apiserver_client.private_key))
      binding_db: *database

# Pruner Instance Group
- name: pruner
  azs:
  - z1
  instances: 1
  networks:
  - name: default
  stemcell: default
  vm_type: default
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul_common: {from: consul_common_link, deployment: cf}
      consul_server: nil
      consul_client: {from: consul_client_link, deployment: cf}
  - name: pruner
    release: app-autoscaler
    properties:
      appmetrics_db: *database
      instancemetrics_db: *database
      scalingengine_db: *database
      pruner:
        logging:
          level: debug 

# Metric-collector Instance Group
- name: metricscollector
  azs:
  - z1
  instances: 1
  networks:
  - name: default
  stemcell: default
  vm_type: default
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul_common: {from: consul_common_link, deployment: cf}
      consul_server: nil
      consul_client: {from: consul_client_link, deployment: cf}
  - name: metricscollector
    release: app-autoscaler
    properties:
      instancemetrics_db: *database
      policy_db: *database
      cf: &cf_credentials
        api: "https://api.((system_domain))"
        grant_type: password
        username: admin
        password: "((cf_admin_password))"
        client_id: admin
        secret: "((cf_admin_client_secret))"
      metricscollector:
        logging:
          level: debug
        server:
          port: 6103
        ca_cert: ((metricscollector_ca.ca))
        server_cert: ((metricscollector_server.certificate))
        server_key: ((metricscollector_server.private_key))

# Event-Generator Instance Group
- name: eventgenerator
  azs:
  - z1
  instances: 1
  networks:
  - name: default
  stemcell: default
  vm_type: default
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul_common: {from: consul_common_link, deployment: cf}
      consul_server: nil
      consul_client: {from: consul_client_link, deployment: cf}
  - name: eventgenerator
    release: app-autoscaler
    properties:
      appmetrics_db: *database
      policy_db: *database
      eventgenerator:
        logging:
          level: debug
        scaling_engine:
          ca_cert: ((scalingengine_ca.ca))
          client_cert: ((scalingengine_client.certificate))
          client_key: ((scalingengine_client.private_key))
        metricscollector:
          ca_cert: ((metricscollector_ca.ca))
          client_cert: ((metricscollector_client.certificate))
          client_key: ((metricscollector_client.private_key))

# Scaling-Engine Instance Group
- name: scalingengine
  azs:
  - z1
  instances: 1
  networks:
  - name: default
  stemcell: default
  vm_type: default
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul_common: {from: consul_common_link, deployment: cf}
      consul_server: nil
      consul_client: {from: consul_client_link, deployment: cf}
  - name: scalingengine
    release: app-autoscaler
    properties:
      scalingengine_db: *database
      scheduler_db: *database
      policy_db: *database
      cf: *cf_credentials
      scalingengine:
        logging:
          level: debug
        server:
          port: 6104
        ca_cert: ((scalingengine_ca.ca))
        server_cert: ((scalingengine_server.certificate))
        server_key: ((scalingengine_server.private_key))
        consul:
          cluster: http://127.0.0.1:8500

variables:
- name: database_password
  type: password
- name: scalingengine_ca
  type: certificate
  options:
    is_ca: true
    common_name: scalingengineCA
- name: scalingengine_server
  type: certificate
  options:
    ca: scalingengine_ca
    common_name: scalingengine.service.cf.internal
    extended_key_usage:
    - client_auth
    - server_auth
- name: scalingengine_client
  type: certificate
  options:
    ca: scalingengine_ca
    common_name: scalingengine client
    extended_key_usage:
    - client_auth
- name: metricscollector_ca
  type: certificate
  options:
    is_ca: true
    common_name: metricscollectorCA
- name: metricscollector_server
  type: certificate
  options:
    ca: metricscollector_ca
    common_name: metricscollector.service.cf.internal
    extended_key_usage:
    - client_auth
    - server_auth
- name: metricscollector_client
  type: certificate
  options:
    ca: metricscollector_ca
    common_name: metricscollector client
    extended_key_usage:
    - client_auth
- name: apiserver_ca
  type: certificate
  options:
    is_ca: true
    common_name: apiserverCA
- name: apiserver_server
  type: certificate
  options:
    ca: apiserver_ca
    common_name: apiserver.service.cf.internal
    extended_key_usage:
    - client_auth
    - server_auth
- name: apiserver_client
  type: certificate
  options:
    ca: apiserver_ca
    common_name: apiserver client
    extended_key_usage:
    - client_auth
- name: servicebroker_ca
  type: certificate
  options:
    is_ca: true
    common_name: servicebrokerCA
- name: servicebroker_server
  type: certificate
  options:
    ca: servicebroker_ca
    common_name: servicebroker.service.cf.internal
    extended_key_usage:
    - client_auth
    - server_auth
- name: scheduler_ca
  type: certificate
  options:
    is_ca: true
    common_name: schedulerCA
- name: scheduler_server
  type: certificate
  options:
    ca: scheduler_ca
    common_name: scheduler.service.cf.internal
    extended_key_usage:
    - client_auth
    - server_auth
- name: scheduler_client
  type: certificate
  options:
    ca: scheduler_ca
    common_name: scheduler client
    extended_key_usage:
    - client_auth