project: app-runtime-interfaces-wg
region: europe-west3
zone: europe-west3-a
secondary_zone: europe-west3-b

#concourse_url: https://concourse.app-runtime-interfaces.ci.cloudfoundry.org

gcs_bucket: terraform-state-wg-ci
gcs_prefix: refactor


# A name-prefix to build resource names from
gke_name: wg-ci-refactor


# source:
#   concourse_infra:
#     url: https://github.com/marcinkubica/bosh-community-stemcell-ci-infra.git//terraform/concourse-infra
#     ref: terraform


sql_instance_tier: db-custom-1-4096
sql_instance_backup_location: eu
sql_instance_disk_size: 38
