---
apiVersion: secretgen.k14s.io/v1alpha1
kind: SSHKey
metadata:
  name: host-key
  namespace: concourse

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: SSHKey
metadata:
  name: worker-key
  namespace: concourse

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: RSAKey
metadata:
  name: session-signing-key
  namespace: concourse

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: local-user
  namespace: concourse

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: concourse-web
  namespace: concourse
spec:
  inputResources:
  - name: host-key
    ref:
      apiVersion: v1
      kind: Secret
      name: host-key
  - name: session-signing-key
    ref:
      apiVersion: v1
      kind: Secret
      name: session-signing-key
  - name: worker-key
    ref:
      apiVersion: v1
      kind: Secret
      name: worker-key
  - name: local-user
    ref:
      apiVersion: v1
      kind: Secret
      name: local-user
  - name: concourse-postgresql-password
    ref:
      apiVersion: v1
      kind: Secret
      name: concourse-postgresql-password
  - name: credhub-admin-client-credentials
    ref:
      apiVersion: v1
      kind: Secret
      name: credhub-admin-client-credentials
  - name: credhub-root-ca
    ref:
      apiVersion: v1
      kind: Secret
      name: credhub-root-ca
  - name: github
    ref:
      apiVersion: v1
      kind: Secret
      name: github
  template:
    data:
      host-key: '$(.host-key.data.ssh-privatekey)'
      session-signing-key: '$(.session-signing-key.data.key\.pem)'
      worker-key-pub: '$(.worker-key.data.ssh-authorizedkey)'
#!      local-users: "local-ci:'$(.local-user.data.password)'"
      postgresql-password: '$(.concourse-postgresql-password.data.password)'
      credhub-client-secret: '$(.credhub-admin-client-credentials.data.password)'
      credhub-ca-cert: '$(.credhub-root-ca.data.certificate)'
      github-client-id: '$(.github.data.id)'
      github-client-secret: '$(.github.data.secret)'
    stringData:
      postgresql-user: "concourse"
      credhub-client-id: "credhub_admin_client"


---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: concourse-worker
  namespace: concourse
spec:
  inputResources:
  - name: host-key
    ref:
      apiVersion: v1
      kind: Secret
      name: host-key
  - name: worker-key
    ref:
      apiVersion: v1
      kind: Secret
      name: worker-key
  template:
    data:
      host-key-pub: '$(.host-key.data.ssh-authorizedkey)'
      worker-key: '$(.worker-key.data.ssh-privatekey)'
