#!/bin/bash

set -e

RUN_DIR=/var/vcap/sys/run/pruner
LOG_DIR=/var/vcap/sys/log/pruner
CONF_DIR=/var/vcap/jobs/pruner/config
PIDFILE=$RUN_DIR/pruner.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "pruner"

    mkdir -p $RUN_DIR
    chown -R vcap:vcap $RUN_DIR
    mkdir -p $LOG_DIR
    chown -R vcap:vcap $LOG_DIR

    echo $$ > $PIDFILE
    
    exec /var/vcap/packages/pruner/pruner -c $CONF_DIR/pruner.yml >>$LOG_DIR/pruner.stdout.log 2>>$LOG_DIR/pruner.stderr.log
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  *)
  echo "Usage: pruner_ctl {start|stop}" ;;
esac
exit 0