#!/bin/bash

set -e

RUN_DIR=/var/vcap/sys/run/operator
LOG_DIR=/var/vcap/sys/log/operator
CONF_DIR=/var/vcap/jobs/operator/config
PIDFILE=$RUN_DIR/operator.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "operator"

    mkdir -p $RUN_DIR
    chown -R vcap:vcap $RUN_DIR
    mkdir -p $LOG_DIR
    chown -R vcap:vcap $LOG_DIR

    echo $$ > $PIDFILE
    
    exec /var/vcap/packages/operator/operator -c $CONF_DIR/operator.yml >>$LOG_DIR/operator.stdout.log 2>>$LOG_DIR/operator.stderr.log
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  *)
  echo "Usage: operator_ctl {start|stop}" ;;
esac
exit 0