// Code generated by counterfeiter. DO NOT EDIT.
package appfakes

import (
	"sync"
	"time"

	"code.cloudfoundry.org/app-autoscaler-release/src/acceptance/assets/app/go_app/internal/app"
)

type FakeCPUWaster struct {
	IsRunningStub        func() bool
	isRunningMutex       sync.RWMutex
	isRunningArgsForCall []struct {
	}
	isRunningReturns struct {
		result1 bool
	}
	isRunningReturnsOnCall map[int]struct {
		result1 bool
	}
	StopTestStub        func()
	stopTestMutex       sync.RWMutex
	stopTestArgsForCall []struct {
	}
	UseCPUStub        func(uint64, time.Duration)
	useCPUMutex       sync.RWMutex
	useCPUArgsForCall []struct {
		arg1 uint64
		arg2 time.Duration
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCPUWaster) IsRunning() bool {
	fake.isRunningMutex.Lock()
	ret, specificReturn := fake.isRunningReturnsOnCall[len(fake.isRunningArgsForCall)]
	fake.isRunningArgsForCall = append(fake.isRunningArgsForCall, struct {
	}{})
	stub := fake.IsRunningStub
	fakeReturns := fake.isRunningReturns
	fake.recordInvocation("IsRunning", []interface{}{})
	fake.isRunningMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCPUWaster) IsRunningCallCount() int {
	fake.isRunningMutex.RLock()
	defer fake.isRunningMutex.RUnlock()
	return len(fake.isRunningArgsForCall)
}

func (fake *FakeCPUWaster) IsRunningCalls(stub func() bool) {
	fake.isRunningMutex.Lock()
	defer fake.isRunningMutex.Unlock()
	fake.IsRunningStub = stub
}

func (fake *FakeCPUWaster) IsRunningReturns(result1 bool) {
	fake.isRunningMutex.Lock()
	defer fake.isRunningMutex.Unlock()
	fake.IsRunningStub = nil
	fake.isRunningReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeCPUWaster) IsRunningReturnsOnCall(i int, result1 bool) {
	fake.isRunningMutex.Lock()
	defer fake.isRunningMutex.Unlock()
	fake.IsRunningStub = nil
	if fake.isRunningReturnsOnCall == nil {
		fake.isRunningReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isRunningReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeCPUWaster) StopTest() {
	fake.stopTestMutex.Lock()
	fake.stopTestArgsForCall = append(fake.stopTestArgsForCall, struct {
	}{})
	stub := fake.StopTestStub
	fake.recordInvocation("StopTest", []interface{}{})
	fake.stopTestMutex.Unlock()
	if stub != nil {
		fake.StopTestStub()
	}
}

func (fake *FakeCPUWaster) StopTestCallCount() int {
	fake.stopTestMutex.RLock()
	defer fake.stopTestMutex.RUnlock()
	return len(fake.stopTestArgsForCall)
}

func (fake *FakeCPUWaster) StopTestCalls(stub func()) {
	fake.stopTestMutex.Lock()
	defer fake.stopTestMutex.Unlock()
	fake.StopTestStub = stub
}

func (fake *FakeCPUWaster) UseCPU(arg1 uint64, arg2 time.Duration) {
	fake.useCPUMutex.Lock()
	fake.useCPUArgsForCall = append(fake.useCPUArgsForCall, struct {
		arg1 uint64
		arg2 time.Duration
	}{arg1, arg2})
	stub := fake.UseCPUStub
	fake.recordInvocation("UseCPU", []interface{}{arg1, arg2})
	fake.useCPUMutex.Unlock()
	if stub != nil {
		fake.UseCPUStub(arg1, arg2)
	}
}

func (fake *FakeCPUWaster) UseCPUCallCount() int {
	fake.useCPUMutex.RLock()
	defer fake.useCPUMutex.RUnlock()
	return len(fake.useCPUArgsForCall)
}

func (fake *FakeCPUWaster) UseCPUCalls(stub func(uint64, time.Duration)) {
	fake.useCPUMutex.Lock()
	defer fake.useCPUMutex.Unlock()
	fake.UseCPUStub = stub
}

func (fake *FakeCPUWaster) UseCPUArgsForCall(i int) (uint64, time.Duration) {
	fake.useCPUMutex.RLock()
	defer fake.useCPUMutex.RUnlock()
	argsForCall := fake.useCPUArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCPUWaster) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.isRunningMutex.RLock()
	defer fake.isRunningMutex.RUnlock()
	fake.stopTestMutex.RLock()
	defer fake.stopTestMutex.RUnlock()
	fake.useCPUMutex.RLock()
	defer fake.useCPUMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCPUWaster) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ app.CPUWaster = new(FakeCPUWaster)
