#@ load("@ytt:template", "template")
#@ load("@ytt:data", "data")

#@ def add_database_user(name):
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: #@ name
  namespace: concourse
  annotations:
    kapp.k14s.io/owned-for-deletion: ""
    cnrm.cloud.google.com/project-id: #@ data.values.google.project_id
    cnrm.cloud.google.com/state-into-spec: merge
spec:
  resourceID: #@ name
  instanceRef:
    external: #@ data.values.database.instance
  password:
    valueFrom:
      secretKeyRef:
        name: #@ name + "-postgresql-password"
        key: password
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: #@ name + "-postgresql-password"
  namespace: concourse
#@ end

--- #@ template.replace(add_database_user("concourse"))
--- #@ template.replace(add_database_user("credhub"))
--- #@ template.replace(add_database_user("uaa"))

---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config

rebaseRules:
- path: [metadata, annotations, cnrm.cloud.google.com/management-conflict-prevention-policy]
  type: copy
  sources: [new, existing]
  resourceMatchers: &matchers
  - apiVersionKindMatcher:
      apiVersion: sql.cnrm.cloud.google.com/v1beta1
      kind: SQLUser

- path: [metadata, annotations, cnrm.cloud.google.com/mutable-but-unreadable-fields]
  type: copy
  sources: [new, existing]
  resourceMatchers: *matchers

- path: [metadata, annotations, cnrm.cloud.google.com/observed-secret-versions]
  type: copy
  sources: [new, existing]
  resourceMatchers: *matchers