name: 'Pending-Check'
description: 'Creates a github-actions check-run for a workflow'
inputs:
  pending_check:
    required: true
    description: Action to execute - [ create, verify ]
  check_filter:
    description: jq match filter for job names
    required: true
    default: ".*acceptance tests"
    # Note: All jobs to verify need their names to to end consistently
    # (ie. "XYZ acceptance tests") in order to utilise correct filtering of checks.
    # use '.*' to filter all jobs in the workflow.

runs:
  using: 'composite'
  steps:
  - name: Creating the check
    shell: bash
    env:
      ACT_RUN: 'if [ "${ACT}" ] && [ "${ACT_OVERRIDE:-"false"}" == "false" ]; then echo "NOTICE: step is running via ACT - skipping"; exit 0; fi;'
      PR_SHA: "${{ github.event.pull_request.head.sha }}"
      GH_RUN_ID: "${{ github.run_id }}"
      GITHUB_TOKEN: "${{ github.token }}"
      GITHUB_REPOSITORY: "${{ github.repository }}"
      WORKFLOW_NAME: "${{ github.workflow }}"
      PENDING_CHECK: "${{ inputs.pending_check }}"
      CHECK_FILTER: "${{ inputs.check_filter }}"
    run: "${AUTOSCALER_DIR}/.github/actions/pending-check/pending_check.sh"
