name: Create Bosh Release
on:
  pull_request:
  workflow_dispatch:
jobs:
  generate-gosub:
    name: ensure gosub specs are up to date
    runs-on: ubuntu-latest
    steps:
      - name: Trust my checkout
        run: git config --global --add safe.directory "${{ env.GITHUB_WORKSPACE }}"

      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_go

      - name: sync-package-specs
        run: |
          source .envrc
          ./scripts/sync-package-specs

      - name: Check if there is any change
        run: |
          git config --global --add safe.directory "${{ env.GITHUB_WORKSPACE }}"; \
            [ $(git status --porcelain | wc -l) -eq 0 ] || \
            { \
              git status;\
              echo "::error::Specs are out of date, run ./scripts/update && ./scripts/sync-package-specs to update";\
              exit 1;\
            }

  bosh-release:
    needs: generate-gosub
    name: Create Bosh Release
    runs-on: ubuntu-latest
    env:
      MAVEN_VERSION: 3.6.3
      MAVEN_SHA: c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_go
      - uses: ./.github/actions/setup_java
        with:
          version: 11

      - name: Install BOSH CLI
        run: |
          brew install cloudfoundry/tap/bosh-cli

      - name: Run Update
        run: |
          set -e
          export PATH=$PATH:/usr/local/maven/bin
          ./scripts/update

      - name: Build Dev Release
        id: build
        uses: orange-cloudfoundry/bosh-release-action@v1.3.0

      - name: Compile Dev Release
        uses: cloudfoundry/bosh-compile-action@main
        with:
          file: ${{ steps.build.outputs.file }}
          args: --guess --debug
