- type: remove
  path: /instance_groups/name=postgres/jobs/name=postgres/properties/databases/tls

- type: replace
  path: /instance_groups/name=postgres/jobs/name=postgres/properties/databases/sslmode
  value: disable

- type: replace
  path: /instance_groups/name=metricsforwarder/jobs/name=metricsforwarder/properties/autoscaler/policy_db/sslmode
  value: disable

- type: replace
  path: /instance_groups/name=metricsforwarder/jobs/name=metricsforwarder/properties/autoscaler/storedprocedure_db/sslmode
  value: disable

- type: replace
  path: /instance_groups/name=scalingengine/jobs/name=scalingengine/properties/autoscaler/policy_db/sslmode
  value: disable

- type: replace
  path: /instance_groups/name=scalingengine/jobs/name=scalingengine/properties/autoscaler/scalingengine_db/sslmode
  value: disable

- type: replace
  path: /instance_groups/name=scalingengine/jobs/name=scalingengine/properties/autoscaler/scheduler_db/sslmode
  value: disable

- type: replace
  path: /instance_groups/name=apiserver/jobs/name=golangapiserver/properties/autoscaler/policy_db/sslmode
  value: disable

- type: replace
  path: /instance_groups/name=apiserver/jobs/name=golangapiserver/properties/autoscaler/binding_db/sslmode
  value: disable

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=scheduler/properties/autoscaler/policy_db/sslmode
  value: disable

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=scheduler/properties/autoscaler/scheduler_db/sslmode
  value: disable

- type: replace
  path: /instance_groups/name=operator/jobs/name=operator/properties/autoscaler/appmetrics_db/sslmode
  value: disable

- type: replace
  path: /instance_groups/name=operator/jobs/name=operator/properties/autoscaler/lock_db/sslmode
  value: disable

- type: replace
  path: /instance_groups/name=operator/jobs/name=operator/properties/autoscaler/policy_db/sslmode
  value: disable

- type: replace
  path: /instance_groups/name=operator/jobs/name=operator/properties/autoscaler/scalingengine_db/sslmode
  value: disable

- type: replace
  path: /instance_groups/name=eventgenerator/jobs/name=eventgenerator/properties/autoscaler/policy_db/sslmode
  value: disable

- type: replace
  path: /instance_groups/name=eventgenerator/jobs/name=eventgenerator/properties/autoscaler/appmetrics_db/sslmode
  value: disable

- type: replace
  path: /instance_groups/name=eventgenerator/jobs/name=eventgenerator/properties/autoscaler/lock_db/sslmode
  value: disable

