name: Acceptance Tests Cleanup (Buildin)
on:
  pull_request:
    types: [ closed ]
    paths:
      - 'src/acceptance/**'

env:
  BUILDIN_MODE: true
  SERVICE_OFFERING_ENABLED: false
  PR_NUMBER: "${{ github.event.pull_request.number }}"
  DEPLOYMENT_NAME: "autoscaler-buildin-${{ github.event.pull_request.number }}"
  BBL_STATE_PATH: "${{ github.workspace }}/bbl/bbl-state"
  AUTOSCALER_DIR: "${{ github.workspace }}/app-autoscaler-release"
  CI_DIR: "${{ github.workspace }}/app-autoscaler-release/ci"

jobs:
  deployment_cleanup:
    name: Cleanup deployments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: app-autoscaler-release
          ref: main
      - uses: ./app-autoscaler-release/.github/actions/setup-environment
        with:
          ssh-key: ${{ secrets.BBL_SSH_KEY }}

      - run: |
          cd ${{ env.AUTOSCALER_DIR }}
          make deploy-cleanup
