name: 'Setup Java'
description: 'Determine the correct java version and set go up'
inputs:
  version:  # id of input
    description: 'The java version that is required'
    default: 11

runs:
  using: "composite"
  steps:
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.version }}

    - name: act only - Install Maven
      if: ${{ env.ACT }}
      shell: bash
      run: |
        set -x
        curl -sL -O https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
        echo "${{ env.MAVEN_SHA }} apache-maven-${MAVEN_VERSION}-bin.tar.gz" | sha512sum -c -
        sudo tar xzf apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /usr/local
        pushd /usr/local > /dev/null
          sudo ln -s apache-maven-${MAVEN_VERSION} maven
        popd  > /dev/null
        echo "/usr/local/maven/bin" >> $GITHUB_PATH
        mvn --version