#!/bin/bash

set -e

JOB_DIR=/var/vcap/jobs/metricsgateway
RUN_DIR=/var/vcap/sys/run/metricsgateway
LOG_DIR=/var/vcap/sys/log/metricsgateway
CONF_DIR=/var/vcap/jobs/metricsgateway/config
HOOK_LOG_OUT=${LOG_DIR}/hooks.stdout.log
HOOK_LOG_ERR=${LOG_DIR}/hooks.stderr.log
PIDFILE=$RUN_DIR/metricsgateway.pid
COMMON_DIR=/var/vcap/packages/common

source $COMMON_DIR/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "metricsgateway"

    ulimit -n 8192

    mkdir -p $RUN_DIR
    chown -R vcap:vcap $RUN_DIR
    mkdir -p $LOG_DIR
    chown -R vcap:vcap $LOG_DIR

    echo $$ > $PIDFILE

    <% unless p("autoscaler.metricsgateway.hooks.pre_start").empty? %>
    $COMMON_DIR/call-hooks.sh "metricsgateway" "pre-start"
    <% end %>

    set_ulimits
    exec /var/vcap/packages/metricsgateway/metricsgateway -c $CONF_DIR/metricsgateway.yml >>$LOG_DIR/metricsgateway.stdout.log 2>>$LOG_DIR/metricsgateway.stderr.log

    <% unless p("autoscaler.metricsgateway.hooks.post_start").empty? %>
    $COMMON_DIR/call-hooks.sh "metricsgateway" "post-start"
    <% end %>
    ;;

  stop)

    <% unless p("autoscaler.metricsgateway.hooks.pre_stop").empty? %>
    $COMMON_DIR/call-hooks.sh "metricsgateway" "pre-stop"
    <% end %>

    kill_and_wait $PIDFILE

    <% unless p("autoscaler.metricsgateway.hooks.post_stop").empty? %>
    $COMMON_DIR/call-hooks.sh "metricsgateway" "post-stop"
    <% end %>
    ;;

  *)
  echo "Usage: metricsgateway_ctl {start|stop}" ;;
esac
exit 0
