---
jobs:
- name: job
  public: true
  plan:
  - task: simple-task
    params:
      SECRET: ((test-secret))
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: ubuntu }
      run:
        path: sh
        args:
          - -ec
          - |
            echo; echo Hello world! My secret is: $SECRET

