# yet another workflow which has been broken some time ago and didn't run
# - the issue was introduced by Setup Environment. Got it working but suspecting it's trying to load non existing ops files
# https://github.com/cloudfoundry/app-autoscaler-release/actions/runs/3741430761/jobs/6351028240#step:6:1
# https://github.com/cloudfoundry/app-autoscaler-release/actions/runs/3741430761/jobs/6351028240#step:7:1

name: ARC – Manifest Tests
on:
  pull_request: # TODO: Please uncomment the lines below!
    # paths:
    #   - 'templates/**'
    #   - 'jobs/**'
    #   - 'packages/**'

concurrency:
  group: "${{ github.workflow }}/${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test_manifest:
    name: Manifest Tests
    runs-on: self-hosted
    container:
      image: ghcr.io/cloudfoundry/app-autoscaler-release-tools:main
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: app-autoscaler-release

      - name: Setup environment
        uses: ./app-autoscaler-release/.github/actions/setup-environment
        with:
          ssh-key: ${{ secrets.bbl_ssh_key}}

      - name: Run Tests - old manifest
        run: |
          set -euo pipefail
          pwd

          pushd app-autoscaler-release/templates
            MANIFEST_PATH=$PWD/../templates/app-autoscaler-deployment.yml \
            OPERATION_DIR_PATH=$PWD/../example/operation \
            SCALINGENGINE_INSTANCE_GROUP=asactors\
            SCHEDULER_INSTANCE_GROUP=asactors\
            METICSFORWARDER_INSTANCE_GROUP=asapi\
            OPERATOR_INSTANCE_GROUP=asactors\
            EVENTGENERATOR_INSTANCE_GROUP=asmetrics\
            METIRCSSERVER_INSTANCE_GROUP=asmetrics\
            METRICSGATEWAY_INSTANCE_GROUP=asnozzle \
            ./manifest_tests.sh
          popd

      - name: Run Tests - Manifest
        run: |
          set -e

          pushd app-autoscaler-release/templates
            MANIFEST_PATH=$PWD/app-autoscaler.yml \
            OPERATION_DIR_PATH=$PWD/../operations \
            ./manifest_tests.sh
          popd
