name: 'Setup Java'
description: 'Determine the correct java version and set go up'
inputs:
  version:  # id of input
    description: 'The java version that is required'
    required: false
  source:
    description: "The source to check for the java version"
    required: false
    default: .

runs:
  using: "composite"
  steps:
    - id: get-version
      shell: bash
      run: |
        if [ -z "${{ inputs.version }}" ]; then
          VERSION=$(grep -E -m 1 -o '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+' ${{ inputs.source }}/packages/openjdk-17/version  | head -1)
          echo "::set-output name=version::${VERSION}"
          echo "Using automatically determined version ${VERSION}"
        else
          echo "::set-output name=version::${{ inputs.version }}"
          echo "Using overridden version ${{ inputs.version }}"
        fi

    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ steps.get-version.outputs.version }}

    - name: act only - Install Maven
      if: ${{ env.ACT }}
      shell: bash
      run: |
        set -x
        curl -sL -O https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
        echo "${{ env.MAVEN_SHA }} apache-maven-${MAVEN_VERSION}-bin.tar.gz" | sha512sum -c -
        sudo tar xzf apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /usr/local
        echo "/usr/local/apache-maven-${MAVEN_VERSION}/bin" >> $GITHUB_PATH
        /usr/local/apache-maven-${MAVEN_VERSION}/bin/mvn --version
