apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: concourse-worker
  labels:
    app: concourse-worker
    chart: concourse-17.0.27
    release: concourse
    heritage: Helm
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: concourse-worker
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: concourse-worker
  labels:
    app: concourse-worker
    chart: concourse-17.0.27
    release: concourse
    heritage: Helm
data:
  pre-stop-hook.sh: |
    #!/bin/bash
    kill -s SIGUSR2 1
    while [ -e /proc/1 ]; do sleep 1; done
---
apiVersion: v1
kind: Service
metadata:
  name: concourse-web
  labels:
    app: concourse-web
    chart: concourse-17.0.27
    release: concourse
    heritage: Helm
spec:
  type: LoadBalancer
  loadBalancerIP: 34.141.111.11
  ports:
  - name: atc
    port: 80
    targetPort: atc
  - name: atc-tls
    port: 443
    targetPort: atc-tls
  selector:
    app: concourse-web
---
apiVersion: v1
kind: Service
metadata:
  name: concourse-web-worker-gateway
  labels:
    app: concourse-web
    chart: concourse-17.0.27
    release: concourse
    heritage: Helm
spec:
  type: ClusterIP
  ports:
  - name: worker-gateway
    port: 2222
    targetPort: tsa
  selector:
    app: concourse-web
---
apiVersion: v1
kind: Service
metadata:
  name: concourse-worker
  labels:
    app: concourse-worker
    chart: concourse-17.0.27
    release: concourse
    heritage: Helm
spec:
  type: ClusterIP
  clusterIP: None
  ports: []
  selector:
    app: concourse-worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concourse-web
  labels:
    app: concourse-web
    chart: concourse-17.0.27
    release: concourse
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concourse-web
      release: concourse
  template:
    metadata:
      labels:
        app: concourse-web
        release: concourse
    spec:
      serviceAccountName: default
      initContainers:
      - name: concourse-migration
        image: concourse/concourse:7.8.1
        args:
        - migrate
        - --migrate-to-latest-version
        env:
        - name: CONCOURSE_POSTGRES_HOST
          value: 127.0.0.1
        - name: CONCOURSE_POSTGRES_PORT
          value: "5432"
        - name: CONCOURSE_POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: concourse-web
              key: postgresql-user
        - name: CONCOURSE_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: concourse-web
              key: postgresql-password
        - name: CONCOURSE_POSTGRES_SSLMODE
          value: disable
        - name: CONCOURSE_POSTGRES_CONNECT_TIMEOUT
          value: 5m
        - name: CONCOURSE_POSTGRES_DATABASE
          value: concourse
        volumeMounts: null
      containers:
      - name: concourse-web
        image: concourse/concourse:7.8.1
        imagePullPolicy: IfNotPresent
        args:
        - web
        env:
        - name: CONCOURSE_ENABLE_GLOBAL_RESOURCES
          value: "true"
        - name: CONCOURSE_ENABLE_RESOURCE_CAUSALITY
          value: "true"
        - name: CONCOURSE_SECRET_RETRY_ATTEMPTS
          value: "5"
        - name: CONCOURSE_SECRET_RETRY_INTERVAL
          value: 1s
        - name: CONCOURSE_LOG_LEVEL
          value: info
        - name: CONCOURSE_BIND_PORT
          value: "80"
        - name: CONCOURSE_BIND_IP
          value: 0.0.0.0
        - name: CONCOURSE_TLS_BIND_PORT
          value: "443"
        - name: CONCOURSE_EXTERNAL_URL
          value: https://concourse.app-runtime-interfaces.ci.cloudfoundry.org
        - name: CONCOURSE_DEBUG_BIND_IP
          value: 127.0.0.1
        - name: CONCOURSE_DEBUG_BIND_PORT
          value: "8079"
        - name: CONCOURSE_INTERCEPT_IDLE_TIMEOUT
          value: 0m
        - name: CONCOURSE_GLOBAL_RESOURCE_CHECK_TIMEOUT
          value: 1h
        - name: CONCOURSE_RESOURCE_CHECKING_INTERVAL
          value: 1m
        - name: CONCOURSE_RESOURCE_WITH_WEBHOOK_CHECKING_INTERVAL
          value: 1m
        - name: CONCOURSE_CONTAINER_PLACEMENT_STRATEGY
          value: volume-locality
        - name: CONCOURSE_BAGGAGECLAIM_RESPONSE_HEADER_TIMEOUT
          value: 1m
        - name: CONCOURSE_BUILD_TRACKER_INTERVAL
          value: 10s
        - name: CONCOURSE_POSTGRES_HOST
          value: 127.0.0.1
        - name: CONCOURSE_POSTGRES_PORT
          value: "5432"
        - name: CONCOURSE_POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: concourse-web
              key: postgresql-user
        - name: CONCOURSE_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: concourse-web
              key: postgresql-password
        - name: CONCOURSE_POSTGRES_SSLMODE
          value: disable
        - name: CONCOURSE_POSTGRES_CONNECT_TIMEOUT
          value: 5m
        - name: CONCOURSE_POSTGRES_DATABASE
          value: concourse
        - name: CONCOURSE_CREDHUB_CA_CERT
          value: /concourse-credhub/ca.cert
        - name: CONCOURSE_CREDHUB_URL
          value: https://credhub.concourse.svc.cluster.local:9000
        - name: CONCOURSE_CREDHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: concourse-web
              key: credhub-client-id
        - name: CONCOURSE_CREDHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: concourse-web
              key: credhub-client-secret
        - name: CONCOURSE_GC_INTERVAL
          value: 30s
        - name: CONCOURSE_GC_ONE_OFF_GRACE_PERIOD
          value: 5m
        - name: CONCOURSE_GC_MISSING_GRACE_PERIOD
          value: 5m
        - name: CONCOURSE_AUTH_DURATION
          value: 24h
        - name: CONCOURSE_SESSION_SIGNING_KEY
          value: /concourse-keys/session_signing_key
        - name: CONCOURSE_MAIN_TEAM_GITHUB_TEAM
          value: cloudfoundry:wg-app-runtime-interfaces-autoscaler-approvers
        - name: CONCOURSE_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: concourse-web
              key: github-client-id
        - name: CONCOURSE_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: concourse-web
              key: github-client-secret
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CONCOURSE_PEER_ADDRESS
          value: $(POD_IP)
        - name: CONCOURSE_TSA_LOG_LEVEL
          value: info
        - name: CONCOURSE_TSA_BIND_IP
          value: 0.0.0.0
        - name: CONCOURSE_TSA_BIND_PORT
          value: "2222"
        - name: CONCOURSE_TSA_DEBUG_BIND_IP
          value: 127.0.0.1
        - name: CONCOURSE_TSA_DEBUG_BIND_PORT
          value: "2221"
        - name: CONCOURSE_TSA_HOST_KEY
          value: /concourse-keys/host_key
        - name: CONCOURSE_TSA_AUTHORIZED_KEYS
          value: /concourse-keys/worker_key.pub
        - name: CONCOURSE_TSA_HEARTBEAT_INTERVAL
          value: 30s
        - name: CONCOURSE_ENABLE_LETS_ENCRYPT
          value: "true"
        ports:
        - name: atc
          containerPort: 80
        - name: atc-tls
          containerPort: 443
        - name: tsa
          containerPort: 2222
        - name: atc-debug
          containerPort: 8079
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/v1/info
            port: atc
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /api/v1/info
            port: atc
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: concourse-keys
          mountPath: /concourse-keys
          readOnly: true
        - name: credhub-keys
          mountPath: /concourse-credhub
          readOnly: true
        - name: auth-keys
          mountPath: /concourse-auth
          readOnly: true
      volumes:
      - name: concourse-keys
        secret:
          secretName: concourse-web
          defaultMode: 256
          items:
          - key: host-key
            path: host_key
          - key: session-signing-key
            path: session_signing_key
          - key: worker-key-pub
            path: worker_key.pub
      - name: credhub-keys
        secret:
          secretName: concourse-web
          defaultMode: 256
          items:
          - key: credhub-ca-cert
            path: ca.cert
      - name: auth-keys
        secret:
          secretName: concourse-web
          defaultMode: 256
          items: null
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concourse-worker
  labels:
    app: concourse-worker
    chart: concourse-17.0.27
    release: concourse
    heritage: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: concourse-worker
      release: concourse
  template:
    metadata:
      labels:
        app: concourse-worker
        release: concourse
    spec:
      nodeSelector:
        cloud.google.com/gke-local-ssd: "true"
      serviceAccountName: default
      tolerations:
      - effect: NoSchedule
        key: workers
        operator: Equal
        value: "true"
      terminationGracePeriodSeconds: 60
      containers:
      - name: concourse-worker
        image: concourse/concourse:7.8.1
        imagePullPolicy: IfNotPresent
        args:
        - worker
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: worker-hc
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 3
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - /pre-stop-hook.sh
        env:
        - name: CONCOURSE_SWEEP_INTERVAL
          value: 30s
        - name: CONCOURSE_CONNECTION_DRAIN_TIMEOUT
          value: 1h
        - name: CONCOURSE_HEALTHCHECK_BIND_IP
          value: 0.0.0.0
        - name: CONCOURSE_HEALTHCHECK_BIND_PORT
          value: "8888"
        - name: CONCOURSE_HEALTHCHECK_TIMEOUT
          value: 5s
        - name: CONCOURSE_EPHEMERAL
          value: "true"
        - name: CONCOURSE_DEBUG_BIND_IP
          value: 127.0.0.1
        - name: CONCOURSE_DEBUG_BIND_PORT
          value: "7776"
        - name: CONCOURSE_WORK_DIR
          value: /concourse-work-dir
        - name: CONCOURSE_BIND_IP
          value: 127.0.0.1
        - name: CONCOURSE_BIND_PORT
          value: "7777"
        - name: CONCOURSE_LOG_LEVEL
          value: info
        - name: CONCOURSE_TSA_HOST
          value: concourse-web-worker-gateway:2222
        - name: CONCOURSE_TSA_PUBLIC_KEY
          value: /concourse-keys/host_key.pub
        - name: CONCOURSE_TSA_WORKER_PRIVATE_KEY
          value: /concourse-keys/worker_key
        - name: CONCOURSE_BAGGAGECLAIM_LOG_LEVEL
          value: info
        - name: CONCOURSE_BAGGAGECLAIM_BIND_IP
          value: 127.0.0.1
        - name: CONCOURSE_BAGGAGECLAIM_BIND_PORT
          value: "7788"
        - name: CONCOURSE_BAGGAGECLAIM_DEBUG_BIND_IP
          value: 127.0.0.1
        - name: CONCOURSE_BAGGAGECLAIM_DEBUG_BIND_PORT
          value: "7787"
        - name: CONCOURSE_BAGGAGECLAIM_BTRFS_BIN
          value: btrfs
        - name: CONCOURSE_BAGGAGECLAIM_MKFS_BIN
          value: mkfs.btrfs
        - name: CONCOURSE_VOLUME_SWEEPER_MAX_IN_FLIGHT
          value: "5"
        - name: CONCOURSE_CONTAINER_SWEEPER_MAX_IN_FLIGHT
          value: "5"
        ports:
        - name: worker-hc
          containerPort: 8888
        resources:
          requests:
            cpu: 3000m
            memory: 512Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: concourse-keys
          mountPath: /concourse-keys
          readOnly: true
        - name: pre-stop-hook
          mountPath: /pre-stop-hook.sh
          subPath: pre-stop-hook.sh
        - mountPath: /concourse-work-dir
          name: concourse-work-dir
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - concourse-workers
            weight: 50
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: concourse-worker
                  release: concourse
      volumes:
      - hostPath:
          path: /mnt/disks/ssd0
        name: concourse-work-dir
      - name: pre-stop-hook
        configMap:
          name: concourse-worker
      - name: concourse-keys
        secret:
          secretName: concourse-worker
          defaultMode: 256
          items:
          - key: host-key-pub
            path: host_key.pub
          - key: worker-key
            path: worker_key
  strategy:
    type: RollingUpdate
