---
final_name: app-autoscaler
blobstore:
  provider: s3
  options:
    bucket_name: sap-hcp-cf
    folder: app-autoscaler-release-blobs
    secret_access_key: bIgMYme+XtcSecdlWfIGyO+DjKLUF2+FgNB0xXdD
    access_key_id: AKIAIL2426JSGJI3CUCA
