#!/bin/bash

set -e

JOB_DIR=/var/vcap/jobs/eventgenerator
RUN_DIR=/var/vcap/sys/run/eventgenerator
LOG_DIR=/var/vcap/sys/log/eventgenerator
CONF_DIR=/var/vcap/jobs/eventgenerator/config
HOOK_LOG_OUT=${LOG_DIR}/hooks.stdout.log
HOOK_LOG_ERR=${LOG_DIR}/hooks.stderr.log
PIDFILE=$RUN_DIR/eventgenerator.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "eventgenerator"

    mkdir -p $RUN_DIR
    chown -R vcap:vcap $RUN_DIR
    mkdir -p $LOG_DIR
    chown -R vcap:vcap $LOG_DIR

    echo $$ > $PIDFILE

    <% unless p("autoscaler.eventgenerator.hooks.pre_start").empty? %>
    ${JOB_DIR}/bin/hooks/call-hooks.sh "pre-start"
    <% end %>

    exec /var/vcap/packages/eventgenerator/eventgenerator -c $CONF_DIR/eventgenerator.yml >>$LOG_DIR/eventgenerator.stdout.log 2>>$LOG_DIR/eventgenerator.stderr.log
  
    <% unless p("autoscaler.eventgenerator.hooks.post_start").empty? %>
    ${JOB_DIR}/bin/hooks/call-hooks.sh "post-start"
    <% end %>
  
    ;;

  stop)
    <% unless p("autoscaler.eventgenerator.hooks.pre_stop").empty? %>
    ${JOB_DIR}/bin/hooks/call-hooks.sh "pre-stop"
    <% end %>

    kill_and_wait $PIDFILE

    <% unless p("autoscaler.eventgenerator.hooks.post_stop").empty? %>
    ${JOB_DIR}/bin/hooks/call-hooks.sh "post-stop"
    <% end %>    
    ;;

  *)
  echo "Usage: eventgenerator_ctl {start|stop}" ;;
esac
exit 0