---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: uaa-admin-client-credentials
  namespace: concourse
spec:
  #! list of resources to read information off
  inputResources:
  - name: uaa-templated-admin-client-credentials
    ref:
      apiVersion: v1
      kind: Secret
      name: uaa-admin-client-credentials-secret
  #! the template that follows a subset of the Secret API
  template:
    #! stringData is used for templating in data that is not base64 encoded
    #! data is used for templating in data that *is* base64 encoded, most likely Secrets.
    stringData:
      admin_client_credentials.yml: |
        oauth:
          clients:
            admin:
              secret: '$(.uaa-templated-admin-client-credentials.data.password)'

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: uaa-admin-client-credentials-secret
  namespace: concourse

