---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: uaa-concourse-user-credentials
  namespace: concourse
spec:
  #! list of resources to read information off
  inputResources:
  - name: uaa-templated-concourse-user-credentials
    ref:
      apiVersion: v1
      kind: Secret
      name: concourse-admin-user-credentials
  #! the template that follows a subset of the Secret API
  template:
    #! stringData is used for templating in data that is not base64 encoded
    stringData:
      concourse_admin_user_credentials.yml: |
        scim:
          users:
          - admin|$(.uaa-templated-concourse-user-credentials.data.password)|admin@admin.tld|first|last|clients.read,clients.write,clients.secret,uaa.admin,scim.read,scim.write,password.write,openid|uaa

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: concourse-admin-user-credentials
  namespace: concourse