---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: uaa-database-credentials
  namespace: concourse
spec:
  #! list of resources to read information off
  inputResources:
  - name: uaa-templated-postgresql-password
    ref:
      apiVersion: v1
      kind: Secret
      name: uaa-postgresql-password
  #! the template that follows a subset of the Secret API
  template:
    #! stringData is used for templating in data that is not base64 encoded
    stringData:
      database_credentials.yml: |
        database:
          username: uaa
          password: '$(.uaa-templated-postgresql-password.data.password)'

#! "uaa-postgresql-password" secret is defined in config/database module
