---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: uaa-encryption-keys
  namespace: concourse
spec:
  #! list of resources to read information off
  inputResources:
  - name: uaa-templated-encryption-key
    ref:
      apiVersion: v1
      kind: Secret
      name: uaa-encryption-key
  #! the template that follows a subset of the Secret API
  template:
    #! stringData is used for templating in data that is not base64 encoded
    stringData:
      encryption_keys.yml: |
        encryption:
          active_key_label: default_encryption_key
          encryption_keys:
          - label: default_encryption_key
            passphrase: '$(.uaa-templated-encryption-key.data.password)'

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: uaa-encryption-key
  namespace: concourse