---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: uaa-jwt-policy-signing-keys
  namespace: concourse
spec:
  #! list of resources to read information off
  inputResources:
  - name: uaa-templated-jwt-keys
    ref:
      apiVersion: v1
      kind: Secret
      name: jwt-keys
  #! the template that follows a subset of the Secret API
  template:
    #! stringData is used for templating in data that is not base64 encoded
    stringData:
      jwt_policy_signing_keys.yml: |
        jwt:
          token:
            policy:
              activeKeyId: default_jwt_policy_key
              keys:
                default_jwt_policy_key:
                  signingKey: '$(.uaa-templated-jwt-keys.data.private-key)'

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: RSAKey
metadata:
  name: jwt-keys
  namespace: concourse
spec:
  secretTemplate:
    type: Opaque
    stringData:
      private-key: $(privateKey)
      public-key: $(publicKey)