---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: uaa-saml-keys
  namespace: concourse
spec:
  #! list of resources to read information off
  inputResources:
  - name: uaa-templated-saml-keys
    ref:
      apiVersion: v1
      kind: Secret
      name: uaa-saml-keys-certs
  #! the template that follows a subset of the Secret API
  template:
    #! stringData is used for templating in data that is not base64 encoded
    stringData:
      saml_keys.yml: |
        login:
          saml:
            activeKeyId: default_saml_key
            keys:
              default_saml_key:
                key: |
                  $(.uaa-templated-saml-keys.data.private_key)
                certificate: |
                  $(.uaa-templated-saml-keys.data.certificate)
                passphrase: ""

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Certificate
metadata:
  name: uaa-saml-keys-ca
  namespace: concourse
spec:
  isCA: true

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Certificate
metadata:
  name: uaa-saml-keys-certs
  namespace: concourse
spec:
  caRef:
    name: uaa-saml-keys-ca
  commonName: uaa_login_service_provider
  secretTemplate:
    stringData:
      certificate: $(certificate)
      private_key: $(privateKey)