name: Manifest Tests
on:
  pull_request:
  workflow_dispatch:
jobs:
  test_manifest:
    name: Manifest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          set -e

          export BOSH_VERSION=6.4.4
          wget -q https://github.com/cloudfoundry/bosh-cli/releases/download/v${BOSH_VERSION}/bosh-cli-${BOSH_VERSION}-linux-amd64 && \
          mv bosh-cli-* /usr/local/bin/bosh && \
          chmod +x /usr/local/bin/bosh

          export YQ_VERSION=4.9.6
          wget -q https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64 && \
          mv yq_linux_amd64 /usr/local/bin/yq && \
          chmod +x /usr/local/bin/yq

      - name: Run Tests - old manifest
        run: |
          set -e

          pushd templates
            MANIFEST_PATH=$PWD/../templates/app-autoscaler-deployment.yml \
            OPERATION_DIR_PATH=$PWD/../example/operation \
            SCALINGENGINE_INSTANCE_GROUP=asactors\
            SCHEDULER_INSTANCE_GROUP=asactors\
            METICSFORWARDER_INSTANCE_GROUP=asapi\
            OPERATOR_INSTANCE_GROUP=asactors\
            EVENTGENERATOR_INSTANCE_GROUP=asmetrics\
            METIRCSSERVER_INSTANCE_GROUP=asmetrics\
            METRICSGATEWAY_INSTANCE_GROUP=asnozzle \
            ./manifest_tests.sh
          popd

      - name: Run Tests - Manifest
        run: |
          set -e

          pushd templates
            MANIFEST_PATH=$PWD/app-autoscaler.yml \
            OPERATION_DIR_PATH=$PWD/../operations \
            ./manifest_tests.sh
          popd
