name: ARC – Manifest Tests
on:
  pull_request:
    ## To do: Please de-comment the lines below!
    # paths:
    #   - 'templates/**'
    #   - 'jobs/**'
    #   - 'packages/**'

concurrency:
  group: "${{ github.workflow }}/${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test_manifest:
    name: Manifest Tests
    runs-on: self-hosted
    container:
      image: ghcr.io/cloudfoundry/app-autoscaler-release-tools:main
    steps:
      - uses: actions/checkout@v3
      - uses: .github/actions/setup-environment
        with:
          ssh-key: ${{ secrets.BBL_SSH_KEY }}

      - name: Run Tests - old manifest
        run: |
          set -euo pipefail

          pushd templates
            MANIFEST_PATH=$PWD/../templates/app-autoscaler-deployment.yml \
            OPERATION_DIR_PATH=$PWD/../example/operation \
            SCALINGENGINE_INSTANCE_GROUP=asactors\
            SCHEDULER_INSTANCE_GROUP=asactors\
            METICSFORWARDER_INSTANCE_GROUP=asapi\
            OPERATOR_INSTANCE_GROUP=asactors\
            EVENTGENERATOR_INSTANCE_GROUP=asmetrics\
            METIRCSSERVER_INSTANCE_GROUP=asmetrics\
            METRICSGATEWAY_INSTANCE_GROUP=asnozzle \
            ./manifest_tests.sh
          popd

      - name: Run Tests - Manifest
        run: |
          set -e

          pushd templates
            MANIFEST_PATH=$PWD/app-autoscaler.yml \
            OPERATION_DIR_PATH=$PWD/../operations \
            ./manifest_tests.sh
          popd
