---
#TODO: mysql timed out creating database (on n2-standard-4)
# https://github.com/cloudfoundry/app-autoscaler-release/actions/runs/3547498182/jobs/5957933700#step:8:15
name: ARC - Build with Mysql

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}/${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        mysql: [8]
        suite: [test, integration]
    env:
      DB_DATABASE: autoscaler
      DB_USER: root
      DB_PASSWORD: root
    runs-on: ubuntu-latest
    # container:
    #   image: ghcr.io/cloudfoundry/app-autoscaler-release-tools:main
    continue-on-error: true
    name: Build suite=${{ matrix.suite }}, jdk=${{ matrix.java }}, mysql=${{ matrix.mysql }}
    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: autoscaler
        ports:
         - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      # - name: Build
      #   run: |
      #     make build db_type=mysql

      - name: ${{ matrix.suite }}
        env:
          DB_HOST: mysql
        run: |
          curl 127.0.0.1:3306
          # make ${{ matrix.suite }} db_type=mysql
