---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-test
    tag: main

params:
  TARGETS:
  AUTOSCALER_DIR: app-autoscaler-release

inputs:
- name: app-autoscaler-release
- name: ci
- name: bbl-state

outputs:
- name: app-autoscaler-release

run:
  path: ci/ci/autoscaler/tasks/make/make.sh
  args: [ app-autoscaler-release ]