#!/bin/bash

set -e

RUN_DIR=/var/vcap/sys/run/metricsforwarder
LOG_DIR=/var/vcap/sys/log/metricsforwarder
CONF_DIR=/var/vcap/jobs/metricsforwarder/config
PIDFILE=$RUN_DIR/metricsforwarder.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "metricsforwarder"

    mkdir -p $RUN_DIR
    chown -R vcap:vcap $RUN_DIR
    mkdir -p $LOG_DIR
    chown -R vcap:vcap $LOG_DIR

    echo $$ > $PIDFILE
    
    exec /var/vcap/packages/metricsforwarder/metricsforwarder -c $CONF_DIR/metricsforwarder.yml >>$LOG_DIR/metricsforwarder.stdout.log 2>>$LOG_DIR/metricsforwarder.stderr.log
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  *)
  echo "Usage: metricsforwarder_ctl {start|stop}" ;;
esac
exit 0