--- 

director_uuid: ((merge))

name: app-autoscaler-release

## Release Details ###
releases:
  - name: app-autoscaler
    version: latest
  - name: postgres
    url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=17
    version: '17'
    sha1: b062e32a5409ccd4e4161337c48705c793a58412
  - name: cf
    version: latest
  - name: routing
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.162.0
    sha1: f17cf09d2414f5f486d18bbd57b17fd48fb69773
    version: '0.162.0'

## Network Section ##
networks:
  - name: default
    type: manual
    subnets:
      - range: 10.244.4.0/24
        reserved: 10.244.4.1
        cloud_properties:
          name: random

## Resource Pool ##
resource_pools:
  - name: default
    network: default
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest

## Disk Pool ##
disk_pools:
  - name: default
    disk_size: 1024

## Canary details ##
update:
  canaries: 1
  canary_watch_time: 1000-300000
  max_in_flight: 3
  update_watch_time: 1000-300000

## Compilation ##
compilation:
  workers: 2
  network: default
  reuse_compilation_vms: false

## Jobs ##
jobs:
  - name: postgres
    instances: (( instance_count_overrides.postgres.instances || 1 ))
    update:
      serial: true
    resource_pool: default
    networks:
      - name: default
    templates:
      - name: consul_agent
        release: cf
        consumes: {consul_client: nil, consul_server: nil, consul_common: nil}
      - name: postgres
        release: postgres
    properties:
      databases: (( default_db ))
      consul:
        agent:
          mode: client
          services:
            postgres:
              check:
                tcp: 127.0.0.1:5432
                interval: 30s
                timeout: 10s
  
  - name: apiserver
    instances: 1
    networks:
      - name: default
    resource_pool: default
    templates:
      - name: consul_agent
        release: cf
        consumes: {consul_client: nil, consul_server: nil, consul_common: nil}
      - name: apiserver
        release: app-autoscaler
      - name: route_registrar
        release: routing
        consumes:
          nats: {from: nats, deployment: cf}
    properties:
      api_server: (( api_server_properties ))
      policy_db: (( policydb ))
      cf:
        api: (( cf_properties.api ))
        skip_ssl_validation: ((cf_properties.skip_ssl_validation))
      consul:
        agent:
          mode: client
          services:
            apiserver: {}
      route_registrar:
        routes:
        - name: api_server_public_api
          registration_interval: 20s
          port: (( api_server_properties.publicPort ))
          tags:
            component: api_server
          uris:
            - autoscaler.bosh-lite.com



  - name: scheduler
    instances: 1
    networks:
      - name: default
    resource_pool: default
    templates:
      - name: consul_agent
        release: cf
        consumes: {consul_client: nil, consul_server: nil, consul_common: nil}
      - name: scheduler
        release: app-autoscaler
    properties:
      scheduler: (( scheduler_properties ))
      scheduler_db: (( schedulerdb ))
      policy_db: (( policydb ))
      consul:
        agent:
          mode: client

  - name: servicebroker
    instances: 1
    networks:
      - name: default
    resource_pool: default
    templates:
      - name: consul_agent
        release: cf
        consumes: {consul_client: nil, consul_server: nil, consul_common: nil}
      - name: servicebroker
        release: app-autoscaler
      - name: route_registrar
        release: routing
        consumes:
          nats: {from: nats, deployment: cf}
    properties:
      service_broker: (( service_broker_properties ))
      binding_db: (( bindingdb ))
      consul:
        agent:
          mode: client
      route_registrar:
            routes:
            - name: autoscaler_service_broker
              registration_interval: 20s
              port: (( service_broker_properties.port ))
              tags:
                component: autoscaler_service_broker
              uris:
                - autoscalerservicebroker.bosh-lite.com


  - name: pruner
    instances: 1
    networks:
      - name: default
    resource_pool: default
    templates:
      - name: consul_agent
        release: cf
        consumes: {consul_client: nil, consul_server: nil, consul_common: nil}
      - name: pruner
        release: app-autoscaler
    properties:
      appmetrics_db: (( appmetricsdb ))
      instancemetrics_db: (( instancemetricsdb ))
      scalingengine_db: (( scalingenginedb ))
      pruner: (( pruner_properties ))
      consul:
        agent:
          mode: client


  - name: metricscollector
    instances: 1
    networks:
      - name: default
    resource_pool: default
    templates:
      - name: consul_agent
        release: cf
        consumes: {consul_client: nil, consul_server: nil, consul_common: nil}
      - name: metricscollector
        release: app-autoscaler
    properties:
      instancemetrics_db: (( instancemetricsdb ))
      policy_db: (( policydb ))
      lock_db: (( lockdb ))
      cf: (( cf_properties ))
      metricscollector: (( metricscollector_properties ))
      consul:
        agent:
          mode: client


  - name: eventgenerator
    instances: 1
    networks:
      - name: default
    resource_pool: default
    templates:
      - name: consul_agent
        release: cf
        consumes: {consul_client: nil, consul_server: nil, consul_common: nil}
      - name: eventgenerator
        release: app-autoscaler
    properties:
      appmetrics_db: (( appmetricsdb ))
      policy_db: (( policydb ))
      eventgenerator: (( eventgenerator_properties ))
      consul:
        agent:
          mode: client

  - name: scalingengine
    instances: 1
    networks:
      - name: default
    resource_pool: default
    templates:
      - name: consul_agent
        release: cf
        consumes: {consul_client: nil, consul_server: nil, consul_common: nil}
      - name: scalingengine
        release: app-autoscaler
    properties:
      scalingengine_db: (( scalingenginedb ))
      scheduler_db: (( schedulerdb ))
      policy_db: (( policydb ))
      cf: (( cf_properties ))
      scalingengine: (( scalingengine_properties ))
      consul:
        agent:
          mode: client

properties:
  consul: (( config_from_cf.consul ))

cf_properties: (( merge )) 
api_server_properties: (( merge )) 
scheduler_properties: (( merge )) 
service_broker_properties: (( merge )) 
pruner_properties: ((merge)) 
metricscollector_properties: (( merge )) 
eventgenerator_properties: (( merge )) 
scalingengine_properties: (( merge )) 
default_db: (( merge )) 
instance_count_overrides: (( merge || nil )) 
database: (( merge || default_db )) 
policydb: (( merge || database )) 
schedulerdb: (( merge || database )) 
scalingenginedb: (( merge || database )) 
appmetricsdb: (( merge || database )) 
instancemetricsdb: (( merge || database )) 
bindingdb: (( merge || database ))
lockdb: (( merge || database ))
config_from_cf: (( merge ))
