--- 

name: (( grab deployment_name ))

## Release Details ###
releases:
- name: app-autoscaler
  version: latest
- name: postgres
  url: file:///repo_local/postgres-release/v17/postgres-release-17.tgz
  version: "17"
- name: routing
  url: file:///repo_local/cf-routing-release/v0.162.0/cf-routing-release-0.162.0.tgz
  version: 0.162.0
- location: file:///repo_local/cfp-cf-release/253.36.0/253.36.0-ibm-cf.tgz 
  name: cf-235031 
  version: ibm-v235.31
- location: file:///repo_local/cfp-unbound/v0.2-15/unbound-v0.2-15.tgz
  name: unbound
  version: v0.2-4

## Network Section ##
networks:
  - name: default
    type: manual
    subnets:
      - range: 10.244.4.0/24
        reserved: 10.244.4.1
        cloud_properties:
          name: random

## Resource Pool ##
resource_pools:
  - name: default
    network: default
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest

## Disk Pool ##
disk_pools:
  - name: default
    disk_size: 1024

## Canary details ##
update:
  canaries: 1
  canary_watch_time: 1000-300000
  max_in_flight: 3
  update_watch_time: 1000-300000

## Compilation ##
compilation:
  workers: 2
  network: default
  reuse_compilation_vms: false

## Jobs ##
jobs:
  - name: postgres
    instances: (( grab instance_count_overrides.postgres.instances || 1 ))
    update:
      serial: true
    resource_pool: (( grab resource_pool ))
    networks:
    - default:
      - dns
      - gateway
      name: default
      static_ips: 
        - (( grab default_db.address))
    templates:
      - name: consul_agent
        release: (( grab meta.cf_release_name ))
        consumes: {consul_client: nil, consul_server: nil, consul_common: nil}
      - name: postgres
        release: postgres
      - name: unbound
        release: unbound
    properties:
      databases: (( grab default_db || null ))
      consul:
        agent:
          mode: client
          services:
            postgres:
              check:
                tcp: 127.0.0.1:5432
                interval: 30s
                timeout: 10s
  
  - name: apiserver
    instances: 1
    networks:
      - name: default
    resource_pool: (( grab resource_pool ))
    templates:
      - name: consul_agent
        release: (( grab meta.cf_release_name ))
        consumes: {consul_client: nil, consul_server: nil, consul_common: nil}
      - name: apiserver
        release: app-autoscaler
      - name: route_registrar
        release: routing
        consumes:
          nats: {deployment: (( grab meta.cf_release_name ))}
      - name: unbound
        release: unbound
    properties:
      api_server: (( grab api_server_properties ))
      policy_db: (( grab policydb ))
      cf:
        api: (( grab cf_properties.api ))
        skip_ssl_validation: (( grab cf_properties.skip_ssl_validation))
      consul:
        agent:
          mode: client
          services:
            apiserver: {}
      route_registrar:
        routes:
        - name: api_server_public_api
          registration_interval: 20s
          port: (( grab api_server_properties.publicPort ))
          tags:
            component: api_server
          uris:
            - (( grab api_server_properties.uri ))



  - name: scheduler
    instances: 1
    networks:
      - name: default
    resource_pool: (( grab resource_pool ))
    templates:
      - name: consul_agent
        release: (( grab meta.cf_release_name ))
        consumes: {consul_client: nil, consul_server: nil, consul_common: nil}
      - name: scheduler
        release: app-autoscaler
      - name: unbound
        release: unbound
    properties:
      scheduler: (( grab scheduler_properties ))
      scheduler_db: (( grab schedulerdb ))
      policy_db: (( grab policydb ))
      consul:
        agent:
          mode: client

  - name: servicebroker
    instances: 1
    networks:
      - name: default
    resource_pool: (( grab resource_pool ))
    templates:
      - name: consul_agent
        release: (( grab meta.cf_release_name )) 
        consumes: {consul_client: nil, consul_server: nil, consul_common: nil}
      - name: servicebroker
        release: app-autoscaler
      - name: route_registrar
        release: routing
        consumes:
          nats: {deployment: (( grab meta.cf_release_name ))}
      - name: unbound
        release: unbound
    properties:
      service_broker: (( grab service_broker_properties ))
      binding_db: (( grab bindingdb ))
      consul:
        agent:
          mode: client
      route_registrar:
            routes:
            - name: autoscaler_service_broker
              registration_interval: 20s
              port: (( grab service_broker_properties.port ))
              tags:
                component: autoscaler_service_broker
              uris:
                - (( grab service_broker_properties.uri ))


  - name: pruner
    instances: 1
    networks:
      - name: default
    resource_pool: (( grab resource_pool ))
    templates:
      - name: consul_agent
        release: (( grab meta.cf_release_name ))
        consumes: {consul_client: nil, consul_server: nil, consul_common: nil}
      - name: pruner
        release: app-autoscaler
      - name: unbound
        release: unbound
    properties:
      appmetrics_db: (( grab appmetricsdb ))
      instancemetrics_db: (( grab instancemetricsdb ))
      scalingengine_db: (( grab scalingenginedb ))
      pruner: (( grab pruner_properties ))
      consul:
        agent:
          mode: client


  - name: metricscollector
    instances: 1
    networks:
      - name: default
    resource_pool: (( grab resource_pool ))
    templates:
      - name: consul_agent
        release: (( grab meta.cf_release_name ))
        consumes: {consul_client: nil, consul_server: nil, consul_common: nil}
      - name: metricscollector
        release: app-autoscaler
      - name: unbound
        release: unbound
    properties:
      instancemetrics_db: (( grab instancemetricsdb ))
      policy_db: (( grab policydb ))
      lock_db: (( grab lockdb ))
      cf: (( grab cf_properties ))
      metricscollector: (( grab metricscollector_properties ))
      consul:
        agent:
          mode: client


  - name: eventgenerator
    instances: 1
    networks:
      - name: default
    resource_pool: (( grab resource_pool ))
    templates:
      - name: consul_agent
        release: (( grab meta.cf_release_name ))
        consumes: {consul_client: nil, consul_server: nil, consul_common: nil}
      - name: eventgenerator
        release: app-autoscaler
      - name: unbound
        release: unbound
    properties:
      appmetrics_db: (( grab appmetricsdb ))
      policy_db: (( grab policydb ))
      eventgenerator: (( grab eventgenerator_properties ))
      consul:
        agent:
          mode: client

  - name: scalingengine
    instances: 1
    networks:
      - name: default
    resource_pool: (( grab resource_pool ))
    templates:
      - name: consul_agent
        release: (( grab meta.cf_release_name ))
        consumes: {consul_client: nil, consul_server: nil, consul_common: nil}
      - name: scalingengine
        release: app-autoscaler
      - name: unbound
        release: unbound
    properties:
      scalingengine_db: (( grab scalingenginedb ))
      scheduler_db: (( grab schedulerdb ))
      policy_db: (( grab policydb ))
      cf: (( grab cf_properties ))
      scalingengine: (( grab scalingengine_properties ))
      consul:
        agent:
          mode: client

properties: (( grab config_from_cf.properties ))