#!/bin/sh

set -e -x

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path=autoscaler-certs
mkdir -p ${depot_path}

# CA to distribute to autoscaler certs
certstrap --depot-path ${depot_path} init --passphrase '' --common-name autoscalerCA
mv -f ${depot_path}/autoscalerCA.crt ${depot_path}/autoscaler-ca.crt
mv -f ${depot_path}/autoscalerCA.key ${depot_path}/autoscaler-ca.key

generate_cert () {
	common_name=$1
	file_name=$2
	certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name $common_name
	certstrap --depot-path ${depot_path} sign $common_name --CA autoscaler-ca
	mv -f ${depot_path}/$common_name.key ${depot_path}/${file_name}.key
	mv -f ${depot_path}/$common_name.csr ${depot_path}/${file_name}.csr
	mv -f ${depot_path}/$common_name.crt ${depot_path}/${file_name}.crt
}

# Generate server certificates for autoscaler components
generate_cert apiserver.service.cf.internal apiserver_server
generate_cert scalingengine.service.cf.internal scalingengine_server
generate_cert metricscollector.service.cf.internal metricscollector_server
generate_cert scheduler.service.cf.internal scheduler_server
generate_cert servicebroker.service.cf.internal servicebroker_server

# Generate client certificates for autoscaler components
generate_cert metricscollector metricscollector_client
generate_cert scalingengine scalingengine_client
generate_cert scheduler scheduler_client
