#!/bin/bash
set -e

# ensure gosub is installed (this will recompile it only if necessary)
go install github.com/garethjevans/gosub@latest

function sync_package() {
  bosh_pkg=${1}
  pkg_src=${2}
  golang_pkg=${3}

  shift
  shift

  (
    set -e

    spec_dir=$PWD/packages/${bosh_pkg}
    echo "Syncing ${bosh_pkg}..."
    cd $PWD/src/${pkg_src}/${golang_pkg}
    {
      cat ${spec_dir}/spec | grep -v '# gosub'
      GO111MODULE=on GOOS=linux gosub list "$@" | grep ${pkg_src} | \
        sed -e 's|code.cloudfoundry.org/app-autoscaler/src/\(.*\)|- \1/* # gosub|g'
      GO111MODULE=on GOOS=linux gosub list "$@" | grep -v ${pkg_src} | \
        sed -e "s|\(.*\)|- ${pkg_src}/vendor/\1/* # gosub|g"
    } > ${spec_dir}/spec.new

    mv ${spec_dir}/spec.new ${spec_dir}/spec
  )
}

export GOPATH=$PWD
export PATH=$GOPATH/bin:$PATH

sync_package eventgenerator autoscaler eventgenerator -app ./...
sync_package golangapiserver autoscaler api -app ./...
sync_package metricsforwarder autoscaler metricsforwarder -app ./...
sync_package metricsgateway autoscaler metricsgateway -app ./...
sync_package metricsserver autoscaler metricsserver -app ./...
sync_package operator autoscaler operator -app ./...
sync_package scalingengine autoscaler scalingengine -app ./...
sync_package acceptance acceptance . -app ./...

