#!/bin/bash
set -e

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

function sync_package() {
  bosh_pkg=${1}

  shift

  (
    set -e

    cd packages/${bosh_pkg}

    {
      cat spec | grep -v '# gosub'
      gosub list "$@" | \
        sed -e 's|\(.*\)|- app-autoscaler/src/\1/*.go # gosub|g'
    } > spec.new

    mv spec.new spec
  )
}

export PATH=$GOPATH/bin:$PATH
export GOPATH=$PWD/src/app-autoscaler

sync_package metricscollector -app  autoscaler/metricscollector/... &
sync_package eventgenerator -app  autoscaler/eventgenerator/... &
sync_package scalingengine -app  autoscaler/scalingengine/... &
sync_package operator -app  autoscaler/operator/... &

wait

git diff --name-only packages/*/spec
