#!/bin/bash
set -euo pipefail

function sync_package() {
  bosh_pkg=${1}
  golang_pkg=${2}

  shift
  shift

  (
    spec_dir=$PWD/packages/${bosh_pkg}
    echo "Syncing ${bosh_pkg}..."
    cd $PWD/src/autoscaler/${golang_pkg}
    {
      cat "${spec_dir}/spec" | grep -v '# gosub'
      go run github.com/loggregator/gosub@master list "$@" | grep autoscaler | \
        sed -e 's|code.cloudfoundry.org/app-autoscaler/src/\(.*\)|- \1/* # gosub|g'
      go run github.com/loggregator/gosub@master list "$@" | grep -v autoscaler | \
        sed -e 's|\(.*\)|- autoscaler/vendor/\1/* # gosub|g'
    } > "${spec_dir}/spec.new"

    mv "${spec_dir}/spec.new" "${spec_dir}/spec"
  )
}

sync_package eventgenerator eventgenerator -app ./...
sync_package golangapiserver api -app ./...
sync_package metricsforwarder metricsforwarder -app ./...
sync_package metricsgateway metricsgateway -app ./...
sync_package metricsserver metricsserver -app ./...
sync_package operator operator -app ./...
sync_package scalingengine scalingengine -app ./...

