#!/bin/bash
git submodule foreach --recursive git submodule sync && git submodule update --init --recursive

pushd src/app-autoscaler/src/autoscaler
  go mod download
  go mod vendor
popd

pushd src/changeloglockcleaner
  go mod download
  go mod vendor
popd
