#!/bin/bash
git submodule foreach --recursive git submodule sync && git submodule update --init --recursive

pushd src/app-autoscaler/src/autoscaler
  go mod download
  go mod vendor
popd

pushd src/changeloglockcleaner
  go mod download
  go mod vendor
popd

pushd src/app-autoscaler/db
  mvn --no-transfer-progress package -DskipTests
popd

pushd src/app-autoscaler/scheduler
  mvn --no-transfer-progress package -DskipTests
popd

