#! /usr/bin/env bash

set -euo pipefail

pushd src/autoscaler > /dev/null
  go mod tidy
  go mod vendor
popd > /dev/null

pushd src/changeloglockcleaner > /dev/null
  go mod tidy
  go mod vendor
popd > /dev/null

pushd src/acceptance > /dev/null
  go mod tidy
  go mod vendor
popd > /dev/null

pushd src/db > /dev/null
  mvn --no-transfer-progress package -DskipTests
popd > /dev/null

pushd src/scheduler > /dev/null
  mvn --no-transfer-progress package -DskipTests
popd > /dev/null
