---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-tools
    tag: main

params:

inputs:
- name: bbl-state
- name: ci

outputs:

run:
  path: ci/ci/infrastructure/scripts/check-for-existing-deployments.sh
