---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-tools
    tag: main
inputs:
  - name: cf-deployment
  - name: ci
outputs:
  - name: combined-ops
run:
  path: ci/ci/infrastructure/scripts/combine-ops.sh
