---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-tools
    tag: main

params:
  SLACK_WEBHOOK:

inputs:
- name: bbl-state
- name: ci
- name: multiapps-controller-artifact-war
- name: multiapps-controller-artifact-yml
- name: multiapps-controller-repo

run:
  path: ci/ci/infrastructure/scripts/deploy-multiapps-controller.sh
