---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-tools
    tag: main

params:
  SLACK_WEBHOOK:

inputs:
- name: bbl-state
- name: ci
- name: prometheus-boshrelease

run:
  path: ci/ci/infrastructure/scripts/deploy-prometheus.sh
