# ==================== Ignore everything by default ====================
*



# ==================== What we actually need ====================
# To react to changes on these files:
!/ci/Dockerfile
!/ci/Dockerfile.dockerignore

!./nix
!/flake.nix
!/flake.lock

!/devbox.json
!/devbox.lock
