# ==================== Ignore everything by default ====================
*



# ==================== What we actually need ====================
!./nix
!/flake.nix
!/flake.lock

!./.devbox
!/devbox.json
!/devbox.lock
