// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BasicAuthentication provides basicAuthentication security value.
	BasicAuthentication(ctx context.Context, operationName string) (BasicAuthentication, error)
}

func (s *Client) securityBasicAuthentication(ctx context.Context, operationName string, req *http.Request) error {
	t, err := s.sec.BasicAuthentication(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BasicAuthentication\"")
	}
	req.SetBasicAuth(t.Username, t.Password)
	return nil
}
