// Code generated by ogen, DO NOT EDIT.

package api

// V1AppsGUIDScalingHistoriesGetParams is parameters of GET /v1/apps/{guid}/scaling_histories operation.
type V1AppsGUIDScalingHistoriesGetParams struct {
	// The GUID identifying the application for which the scaling history is fetched.
	// It can be found in the `application_id` property of the JSON object stored in the
	// `VCAP_APPLICATION` environment variable.
	GUID string
	// The start time in the number of nanoseconds elapsed since January 1, 1970 UTC.
	StartTime OptInt
	// The end time in the number of nanoseconds elapsed since January 1, 1970 UTC.
	EndTime OptInt
	// The sorting order. The scaling history will be order by timestamp ascending or descending.
	OrderDirection OptV1AppsGUIDScalingHistoriesGetOrderDirection
	// The page number to query.
	Page OptInt
	// Number of entries shown per page.
	ResultsPerPage OptInt
}
