#!/bin/bash

set -e

JOB_DIR=/var/vcap/jobs/metricscollector
RUN_DIR=/var/vcap/sys/run/metricscollector
LOG_DIR=/var/vcap/sys/log/metricscollector
CONF_DIR=/var/vcap/jobs/metricscollector/config
HOOK_LOG_OUT=${LOG_DIR}/hooks.stdout.log
HOOK_LOG_ERR=${LOG_DIR}/hooks.stderr.log
PIDFILE=$RUN_DIR/metricscollector.pid
COMMON_DIR=/var/vcap/packages/common

source $COMMON_DIR/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "metricscollector"

    ulimit -n 8192

    mkdir -p $RUN_DIR
    chown -R vcap:vcap $RUN_DIR
    mkdir -p $LOG_DIR
    chown -R vcap:vcap $LOG_DIR

    echo $$ > $PIDFILE

    <% unless p("autoscaler.metricscollector.hooks.pre_start").empty? %>
    $COMMON_DIR/call-hooks.sh "metricscollector" "pre-start"
    <% end %>

    exec /var/vcap/packages/metricscollector/metricscollector -c $CONF_DIR/metricscollector.yml >>$LOG_DIR/metricscollector.stdout.log 2>>$LOG_DIR/metricscollector.stderr.log

    <% unless p("autoscaler.metricscollector.hooks.post_start").empty? %>
    $COMMON_DIR/call-hooks.sh "metricscollector" "post-start"
    <% end %>
    ;;

  stop)

    <% unless p("autoscaler.metricscollector.hooks.pre_stop").empty? %>
    $COMMON_DIR/call-hooks.sh "metricscollector" "pre-stop"
    <% end %>

    kill_and_wait $PIDFILE

    <% unless p("autoscaler.metricscollector.hooks.post_stop").empty? %>
    $COMMON_DIR/call-hooks.sh "metricscollector" "post-stop"
    <% end %>
    ;;

  *)
  echo "Usage: metricscollector_ctl {start|stop}" ;;
esac
exit 0
