#!/bin/bash

set -e

RUN_DIR=/var/vcap/sys/run/metricscollector
LOG_DIR=/var/vcap/sys/log/metricscollector
CONF_DIR=/var/vcap/jobs/metricscollector/config
PIDFILE=$RUN_DIR/metricscollector.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "metricscollector"

    ulimit -n 8192

    mkdir -p $RUN_DIR
    chown -R vcap:vcap $RUN_DIR
    mkdir -p $LOG_DIR
    chown -R vcap:vcap $LOG_DIR

    echo $$ > $PIDFILE

    exec /var/vcap/packages/metricscollector/metricscollector -c $CONF_DIR/metricscollector.yml >>$LOG_DIR/metricscollector.stdout.log 2>>$LOG_DIR/metricscollector.stderr.log
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  *)
  echo "Usage: metricscollector_ctl {start|stop}" ;;
esac
exit 0