#@ load("@ytt:template", "template")
#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudsql-proxy
  namespace: concourse
  labels:
    app: cloudsql-proxy
spec:
  selector:
    matchLabels:
      app: cloudsql-proxy
  template:
    metadata:
      labels:
        app: cloudsql-proxy
    spec:
      serviceAccountName: cloud-sql-auth-proxy
      containers:
      - name: cloudsql-proxy
        image: 'gcr.io/cloudsql-docker/gce-proxy:1.30.1'
        command:
        - /cloud_sql_proxy
        args:
        - --dir=/cloudsql
        - #@ "-instances=" + data.values.google.project_id + ":" + data.values.google.region + ":" + data.values.database.name + "=tcp:0.0.0.0:5432"
        ports:
        - name: cloudsql-port
          containerPort: 5432
          hostPort: 5432
        livenessProbe:
          tcpSocket:
            port: cloudsql-port
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: cloudsql-port
          initialDelaySeconds: 5
          timeoutSeconds: 1
