---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: uaa-credhub-admin-client-credentials
  namespace: concourse
spec:
  #! list of resources to read information off
  inputResources:
  - name: credhub-templated-admin-client-credentials
    ref:
      apiVersion: v1
      kind: Secret
      name: credhub-admin-client-credentials
  - name: credhub-templated-user-client-credentials
    ref:
      apiVersion: v1
      kind: Secret
      name: credhub-client-user-credentials
  #! the template that follows a subset of the Secret API
  template:
    #! stringData is used for templating in data that is not base64 encoded
    stringData:
      credhub_admin_client_credentials.yml: |
        oauth:
          clients:
            credhub_admin_client:
              secret: '$(.credhub-templated-admin-client-credentials.data.password)'
        scim:
          users:
          - credhub_admin_client|$(.credhub-templated-admin-client-credentials.data.password)|credhub@credhub.tld|first|last|credhub.read,credhub.write|uaa
          - credhub_client|$(.credhub-templated-user-client-credentials.data.password)|credhub@credhub.tld|first|last|credhub.read,credhub.write|uaa2

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: credhub-admin-client-credentials
  namespace: concourse

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: credhub-client-user-credentials
  namespace: concourse