---
anchors:

  acceptance-main-env: &acceptance-main-env
    SYSTEM_DOMAIN: "autoscaler.app-runtime-interfaces.ci.cloudfoundry.org"
    DEPLOYMENT_NAME: "acceptance-main"
    SKIP_SSL_VALIDATION: true
    NAME_PREFIX: "acceptance-main"
    BOSH_FIX_RELEASES: true
    GINKGO_OPTS: "--fail-fast"

  acceptance-main-log-cache-env: &acceptance-main-log-cache-env
    SYSTEM_DOMAIN: "autoscaler.app-runtime-interfaces.ci.cloudfoundry.org"
    DEPLOYMENT_NAME: "acceptance-lc-main"
    SKIP_SSL_VALIDATION: true
    NAME_PREFIX: "acceptance-lc-main"
    BOSH_FIX_RELEASES: true
    GINKGO_OPTS: "--fail-fast"

  acceptance-main-buildin-env: &acceptance-main-buildin-env
    SYSTEM_DOMAIN: "autoscaler.app-runtime-interfaces.ci.cloudfoundry.org"
    DEPLOYMENT_NAME: "acceptance-bld-main"
    SKIP_SSL_VALIDATION: true
    NAME_PREFIX: "acceptance-bld-main"
    BOSH_FIX_RELEASES: true
    GINKGO_OPTS: "--fail-fast"
    # Skipped - deployment requires retrofit of make targets
    #BUILDIN_MODE: true
    SERVICE_OFFERING_ENABLED: false

  upgrade-test-env: &upgrade-test-env
    SYSTEM_DOMAIN: "autoscaler.app-runtime-interfaces.ci.cloudfoundry.org"
    DEPLOYMENT_NAME: "upgrade-test"
    SKIP_SSL_VALIDATION: true
    NAME_PREFIX: "upgrade-test"

  app-autoscaler-ops-files: &app-autoscaler-ops-files
    OPS_FILES: |
      operations/add-releases.yml
      operations/instance-identity-cert-from-cf.yml
      operations/add-postgres-variables.yml
      operations/enable-nats-tls.yml
      operations/loggregator-certs-from-cf.yml
      operations/add-extra-plan.yml
      operations/set-release-version.yml

  app-autoscaler-ops-files-log-cache: &app-autoscaler-ops-files-log-cache
    OPS_FILES: |
      operations/add-releases.yml
      operations/instance-identity-cert-from-cf.yml
      operations/add-postgres-variables.yml
      operations/enable-nats-tls.yml
      operations/loggregator-certs-from-cf.yml
      operations/add-extra-plan.yml
      operations/set-release-version.yml
      operations/enable-log-cache.yml
      operations/log-cache-syslog-server.yml

  app-autoscaler-ops-files-upgrade: &app-autoscaler-ops-files-upgrade
    OPS_FILES: |
      operations/add-releases.yml
      operations/instance-identity-cert-from-cf.yml
      operations/add-postgres-variables.yml
      operations/enable-nats-tls.yml
      operations/loggregator-certs-from-cf.yml
      operations/postgres-persistent-disk.yml
      operations/add-extra-plan.yml
      operations/set-release-version.yml

  app-autoscaler-ops-files-buildin: &app-autoscaler-ops-files-buildin
    OPS_FILES: |
      operations/add-releases.yml
      operations/instance-identity-cert-from-cf.yml
      operations/add-postgres-variables.yml
      operations/enable-nats-tls.yml
      operations/loggregator-certs-from-cf.yml
      operations/add-extra-plan.yml
      operations/set-release-version.yml
      operations/enable-log-cache.yml
      operations/log-cache-syslog-server.yml
      operations/use_buildin_mode.yml


groups:
- name: all
  jobs:
  - set-pipeline
  - unit-tests-main
  - integration-tests-main
  - acceptance-main
  - acceptance-main-log-cache
  - acceptance-main-buildin
  - draft
  - release
  - upgrade-test-main
  - update-golang
  - update-java
- name: autoscaler-release
  jobs:
  - set-pipeline
  - unit-tests-main
  - integration-tests-main
  - acceptance-main
  - acceptance-main-log-cache
  - acceptance-main-buildin
  - draft
  - release
  - upgrade-test-main
- name: update-sdks
  jobs:
    - update-golang
    - update-java

resource_types:
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: pull-request
  type: docker-image
  source:
    repository: ghcr.io/bonzofenix/github-pr-resource
    tag: master

- name: github-release
  type: docker-image
  source:
    repository: concourse/github-release-resource

resources:
- name: ci
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/app-autoscaler-release
    private_key: ((autoscaler_git_key))
    branch: main
    fetch_tags: true
    paths:
      - ci
- name: app-autoscaler-release-main
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/app-autoscaler-release
    private_key: ((autoscaler_git_key))
    branch: main
    fetch_tags: true

- name: gh-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: app-autoscaler-release
    access_token: ((autoscaler_access_token))

- name: previous-stable-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/app-autoscaler-release

- name: bbl-state
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/app-autoscaler-env-bbl-state
    private_key: ((autoscaler_bbl_git_key))
    branch: main

- name: release-bucket
  type: gcs-resource
  source:
    bucket: app-autoscaler-releases
    json_key: ((autoscaler_releases_uploader_key))
    regexp: releases/app-autoscaler-v(.*).tgz

- name: acceptance-tests-bucket
  type: gcs-resource
  source:
    bucket: app-autoscaler-releases
    json_key: ((autoscaler_releases_uploader_key))
    regexp: releases/app-autoscaler-acceptance-tests-v(.*).tgz
    initial_path: releases/app-autoscaler-acceptance-tests-v0.0.1.tgz

- name: golang-release
  type: git
  icon: github
  check_every: 5m
  source:
    uri: https://github.com/bosh-packages/golang-release.git
    branch: master
    version_depth: 20

- name: java-release
  type: git
  icon: github
  check_every: 5m
  source:
    uri:  https://github.com/bosh-packages/java-release.git
    branch: master
    version_depth: 20

jobs:
- name: set-pipeline
  public: true
  plan:
  - get: ci
    trigger: true
  - set_pipeline: self
    file: ci/ci/autoscaler/pipeline.yml

- name: unit-tests-main
  public: true
  build_logs_to_retain: 100
  serial: true
  plan:
  - in_parallel:
    - get: app-autoscaler-release-main
      trigger: true
    - get: ci
  - task: run-unit-tests
    file: ci/ci/autoscaler/tasks/run-unit-tests.yml
    attempts: 3
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main


- name: integration-tests-main
  public: true
  build_logs_to_retain: 100
  serial: true
  serial_groups: [integration]
  plan:
  - in_parallel:
    - get: app-autoscaler-release-main
      trigger: true
    - get: ci
  - task: run-integration-tests
    file: ci/ci/autoscaler/tasks/run-integration-tests.yml
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main

- name: acceptance-main
  public: true
  build_logs_to_retain: 100
  serial: true
  ensure:
    task: cleanup
    file: ci/ci/autoscaler/tasks/cleanup-autoscaler.yml
    params:
      <<: *acceptance-main-env
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
  plan:
  - in_parallel:
    - get: bbl-state
    - get: app-autoscaler-release-main
      passed: [unit-tests-main, integration-tests-main]
      trigger: true
    - get: ci
  - task: run-pre-release-script
    file: ci/ci/autoscaler/tasks/run-prerelease-script.yml
    params:
      SCRIPT_NAME: ./scripts/update
    input_mapping:
      release: app-autoscaler-release-main
    output_mapping:
      release: app-autoscaler-release-main
  - task: deploy-autoscaler
    file: ci/ci/autoscaler/tasks/deploy-autoscaler.yml
    params:
      <<: *acceptance-main-env
      <<: *app-autoscaler-ops-files
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
  - task: register-broker
    file: ci/ci/autoscaler/tasks/register-broker.yml
    params:
      <<: *acceptance-main-env
    input_mapping:
      release: app-autoscaler-release-main
  - in_parallel:
    - task: autoscaler-acceptance-api
      attempts: 3
      file: ci/ci/autoscaler/tasks/run-acceptance-tests.yml
      params:
        <<: *acceptance-main-env
        SUITES: api
      input_mapping:
        app-autoscaler-release: app-autoscaler-release-main
    - task: autoscaler-acceptance-app
      attempts: 3
      file: ci/ci/autoscaler/tasks/run-acceptance-tests.yml
      params:
        <<: *acceptance-main-env
        SUITES: app
      input_mapping:
        app-autoscaler-release: app-autoscaler-release-main
    - task: autoscaler-acceptance-broker
      attempts: 3
      file: ci/ci/autoscaler/tasks/run-acceptance-tests.yml
      params:
        <<: *acceptance-main-env
        SUITES: broker
      input_mapping:
        app-autoscaler-release: app-autoscaler-release-main

- name: acceptance-main-log-cache
  public: true
  build_logs_to_retain: 100
  serial: true
  ensure:
    task: cleanup
    file: ci/ci/autoscaler/tasks/cleanup-autoscaler.yml
    params:
      <<: *acceptance-main-log-cache-env
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
  plan:
  - in_parallel:
    - get: bbl-state
    - get: app-autoscaler-release-main
      passed: [unit-tests-main, integration-tests-main]
      trigger: true
    - get: ci
  - task: run-pre-release-script
    file: ci/ci/autoscaler/tasks/run-prerelease-script.yml
    params:
      SCRIPT_NAME: ./scripts/update
    input_mapping:
      release: app-autoscaler-release-main
    output_mapping:
      release: app-autoscaler-release-main
  - task: deploy-autoscaler
    file: ci/ci/autoscaler/tasks/deploy-autoscaler.yml
    params:
      <<: *acceptance-main-log-cache-env
      <<: *app-autoscaler-ops-files-log-cache
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
  - task: register-broker
    file: ci/ci/autoscaler/tasks/register-broker.yml
    params:
      <<: *acceptance-main-log-cache-env
    input_mapping:
      release: app-autoscaler-release-main
  - in_parallel:
    - task: autoscaler-acceptance-api
      attempts: 3
      file: ci/ci/autoscaler/tasks/run-acceptance-tests.yml
      params:
        <<: *acceptance-main-log-cache-env
        SUITES: api
      input_mapping:
        app-autoscaler-release: app-autoscaler-release-main
    - task: autoscaler-acceptance-app
      attempts: 3
      file: ci/ci/autoscaler/tasks/run-acceptance-tests.yml
      params:
        <<: *acceptance-main-log-cache-env
        SUITES: app
      input_mapping:
        app-autoscaler-release: app-autoscaler-release-main
    - task: autoscaler-acceptance-broker
      attempts: 3
      file: ci/ci/autoscaler/tasks/run-acceptance-tests.yml
      params:
        <<: *acceptance-main-log-cache-env
        SUITES: broker
      input_mapping:
        app-autoscaler-release: app-autoscaler-release-main

- name: acceptance-main-buildin
  public: true
  build_logs_to_retain: 100
  serial: true
  ensure:
    task: cleanup
    file: ci/ci/autoscaler/tasks/cleanup-autoscaler.yml
    params:
      <<: *acceptance-main-buildin-env
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
  plan:
  - in_parallel:
    - get: bbl-state
    - get: app-autoscaler-release-main
      passed: [unit-tests-main, integration-tests-main]
      trigger: true
    - get: ci
  - task: run-pre-release-script
    file: ci/ci/autoscaler/tasks/run-prerelease-script.yml
    params:
      SCRIPT_NAME: ./scripts/update
    input_mapping:
      release: app-autoscaler-release-main
    output_mapping:
      release: app-autoscaler-release-main
  - task: deploy-autoscaler
    file: ci/ci/autoscaler/tasks/deploy-autoscaler.yml
    params:
      <<: *acceptance-main-buildin-env
      <<: *app-autoscaler-ops-files-buildin
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
  - in_parallel:
    - task: autoscaler-acceptance-api
      attempts: 3
      file: ci/ci/autoscaler/tasks/run-acceptance-tests.yml
      params:
        <<: *acceptance-main-buildin-env
        BUILDIN_MODE: true
        SUITES: api
      input_mapping:
        app-autoscaler-release: app-autoscaler-release-main
    - task: autoscaler-acceptance-app
      attempts: 3
      file: ci/ci/autoscaler/tasks/run-acceptance-tests.yml
      params:
        <<: *acceptance-main-buildin-env
        BUILDIN_MODE: true
        SUITES: app
      input_mapping:
        app-autoscaler-release: app-autoscaler-release-main

- name: upgrade-test-main
  serial_groups: [infra]
  public: true
  build_logs_to_retain: 100
  ensure:
      task: cleanup
      file: ci/ci/autoscaler/tasks/cleanup-autoscaler.yml
      params:
        <<: *upgrade-test-env
      input_mapping:
        app-autoscaler-release: app-autoscaler-release-main
  plan:
  - in_parallel:
    - get: bbl-state
    - get: ci
    - get: app-autoscaler-release-main
      passed:
      - acceptance-main
      - acceptance-main-log-cache
      - acceptance-main-buildin
      trigger: true
    - get: previous-stable-release
  - task: deploy-previous-stable-release
    file: ci/ci/autoscaler/tasks/deploy-previous-autoscaler.yml
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
    params:
      <<: *upgrade-test-env
      <<: *app-autoscaler-ops-files-upgrade
  - task: register-broker
    file: ci/ci/autoscaler/tasks/register-broker.yml
    params:
      <<: *upgrade-test-env
    input_mapping:
      release: app-autoscaler-release-main
  - task: autoscaler-pre-upgrade
    file: ci/ci/autoscaler/tasks/run-acceptance-tests.yml
    params:
      <<: *upgrade-test-env
      SUITES: |
        pre_upgrade
      NODES: 1
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
  - task: run-pre-release-script
    file: ci/ci/autoscaler/tasks/run-prerelease-script.yml
    params:
      SCRIPT_NAME: ./scripts/update
    input_mapping:
      release: app-autoscaler-release-main
    output_mapping:
      release: app-autoscaler-release-main
  - task: deploy-autoscaler
    file: ci/ci/autoscaler/tasks/deploy-autoscaler.yml
    params:
      <<: *upgrade-test-env
      <<: *app-autoscaler-ops-files-upgrade
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
  - task: autoscaler-post-upgrade
    file: ci/ci/autoscaler/tasks/run-acceptance-tests.yml
    params:
      <<: *upgrade-test-env
      SUITES: |
        post_upgrade
      NODES: 1
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main

- name: release
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: release-bucket
    - get: acceptance-tests-bucket
    - get: gh-release
    - get: app-autoscaler-release-main
      passed: [upgrade-test-main]
    - get: ci
  - task: run-pre-release-script
    file: ci/ci/autoscaler/tasks/run-prerelease-script.yml
    params:
      SCRIPT_NAME: ./scripts/update
    input_mapping:
      release: app-autoscaler-release-main
    output_mapping:
      release: app-autoscaler-release-main
  - task: release-autoscaler
    file: ci/ci/autoscaler/tasks/release-autoscaler.yml
    params:
      UPLOADER_KEY: ((autoscaler_blobstore_uploader_key))
      GITHUB_TOKEN: ((autoscaler_access_token))
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
  - put: release-bucket
    params:
      file: "generated-release/artifacts/app-autoscaler-v*.tgz"
  - put: acceptance-tests-bucket
    params:
      file: "generated-release/artifacts/app-autoscaler-acceptance-tests-v*.tgz"
  - put: gh-release
    params:
      name: generated-release/name
      tag: generated-release/tag
      body: generated-release/changelog.md
      globs: [generated-release/artifacts/*]
      commitish: app-autoscaler-release-main/.git/ref
  - put: app-autoscaler-release-main
    params:
      rebase: true
      repository: pushme/app-autoscaler-release

# TODO move to a github action a possibly make it add the draft release notes to the PR?
#- name: draft-pr
#  public: true
#  build_logs_to_retain: 100
#  plan:
#  - in_parallel:
#    - get: gh-release
#    - get: app-autoscaler-release-main
#    - get: app-autoscaler-release-pr
#      passed: [acceptance-pr]
#      trigger: true
#  - task: dummy-release-autoscaler
#    file: app-autoscaler-release-main/ci/autoscaler/tasks/release-autoscaler.yml
#    params:
#      UPLOADER_KEY: ((autoscaler_blobstore_uploader_key))
#      GITHUB_TOKEN: ((autoscaler_access_token))
#      PERFORM_BOSH_RELEASE: false
#    input_mapping:
#      app-autoscaler-release: app-autoscaler-release-pr


- name: draft
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: gh-release
    - get: app-autoscaler-release-main
      passed: [upgrade-test-main]
      trigger: true
    - get: ci
  - task: dummy-release-autoscaler
    file: ci/ci/autoscaler/tasks/release-autoscaler.yml
    params:
      UPLOADER_KEY: ((autoscaler_blobstore_uploader_key))
      GITHUB_TOKEN: ((autoscaler_access_token))
      PERFORM_BOSH_RELEASE: false
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main


- name: update-golang
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: app-autoscaler-release-main
    - get: java-release
    - get: golang-release
      trigger: true
    - get: ci
  - task: update-golang-sdk
    file: ci/ci/autoscaler/tasks/update-sdk/task.yml
    params:
      type: golang
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main


- name: update-java
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: app-autoscaler-release-main
    - get: java-release
      trigger: true
    - get: golang-release
    - get: ci
  - task: update-java-sdk
    file: ci/ci/autoscaler/tasks/update-sdk/task.yml
    params:
      type: java
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
