---
groups:
- name: autoscaler-release
  jobs:
  - unit-tests-main
  - unit-tests-pr
  - integration-tests-main
  - integration-tests-pr
  - acceptance-main
  - acceptance-pr
  - draft
  - draft-pr
  - release
  - upgrade-test-main
- name: infrastructure
  jobs:
  - setup-infrastructure
  - deploy-cf
- name: cleanup
  jobs:
  - destroy-infrastructure
  - delete-autoscaler
  - delete-cf

resource_types:
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

- name: github-release
  type: docker-image
  source:
    repository: concourse/github-release-resource

resources:
- name: app-autoscaler-release-main
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/app-autoscaler-release
    private_key: ((autoscaler_git_key))
    branch: main
    fetch_tags: true

- name: app-autoscaler-release-pr
  type: pull-request
  check_every: 2m
  source:
    repository: cloudfoundry/app-autoscaler-release
    access_token: ((autoscaler_access_token))
    labels: ["approved", "dependencies"]

- name: gh-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: app-autoscaler-release
    access_token: ((autoscaler_access_token))

- name: previous-stable-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/app-autoscaler-release

- name: app-autoscaler-ci
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/app-autoscaler-ci.git
    branch: master

- name: bbl-state
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/app-autoscaler-env-bbl-state
    private_key: ((autoscaler_git_key))
    branch: main

- name: autoscaler-env-bbl-config
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/app-autoscaler-env-bbl-state
    private_key: ((autoscaler_git_key))
    branch: main
    paths:
    - ./custom-config/*

- name: autoscaler-env-vars-store
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/app-autoscaler-env-bbl-state
    private_key: ((autoscaler_git_key))
    branch: main
    paths:
    - deployment-vars.yml

- name: cf-deployment
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/cf-deployment.git
    branch: main

- name: cf-deployment-concourse-tasks
  type: git
  icon: github
  source:
    branch: main
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
    tag_filter: v12.*

- name: release
  type: gcs-resource
  source:
    bucket: app-autoscaler-releases
    json_key: ((autoscaler_releases_uploader_key))
    regexp: releases/app-autoscaler-v(.*).tgz

jobs:
- name: unit-tests-main
  public: true
  build_logs_to_retain: 100
  serial: true
  plan:
  - in_parallel:
    - get: app-autoscaler-release-main
      trigger: true
    - get: app-autoscaler-ci
  - task: run-unit-tests
    file: app-autoscaler-ci/autoscaler/tasks/run-unit-tests.yml
    attempts: 3
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main




- name: unit-tests-pr
  public: true
  build_logs_to_retain: 100
  serial: true
  plan:
  - in_parallel:
    - get: app-autoscaler-release-pr
      trigger: true
      version: every
      params:
        submodules: true
    - get: app-autoscaler-ci
  - put: app-autoscaler-release-pr
    params:
      path: app-autoscaler-release-pr
      status: pending
      context: unit-tests
    get_params:
      submodules: true
  - task: run-unit-tests
    file: app-autoscaler-ci/autoscaler/tasks/run-unit-tests.yml
    attempts: 3
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-pr
  on_success:
    put: app-autoscaler-release-pr
    params:
      path: app-autoscaler-release-pr
      status: success
      context: unit-tests
  on_failure:
    put: app-autoscaler-release-pr
    params:
      path: app-autoscaler-release-pr
      status: failure
      context: unit-tests



- name: integration-tests-main
  public: true
  build_logs_to_retain: 100
  serial: true
  serial_groups: [integration]
  plan:
  - in_parallel:
    - get: app-autoscaler-release-main
      trigger: true
    - get: app-autoscaler-ci
  - task: run-integration-tests
    file: app-autoscaler-ci/autoscaler/tasks/run-integration-tests.yml
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main


- name: integration-tests-pr
  public: true
  build_logs_to_retain: 100
  serial: true
  serial_groups: [integration]
  plan:
  - in_parallel:
    - get: app-autoscaler-release-pr
      trigger: true
      version: every
      params:
        submodules: true
    - get: app-autoscaler-ci
  - put: app-autoscaler-release-pr
    params:
      path: app-autoscaler-release-pr
      status: pending
      context: integration-tests
    get_params:
      submodules: true
  - task: run-integration-tests
    file: app-autoscaler-ci/autoscaler/tasks/run-integration-tests.yml
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-pr
  on_success:
    put: app-autoscaler-release-pr
    params:
      path: app-autoscaler-release-pr
      status: success
      context: integration-tests
  on_failure:
    put: app-autoscaler-release-pr
    params:
      path: app-autoscaler-release-pr
      status: failure
      context: integration-tests



- name: setup-infrastructure
  serial_groups: [infra]
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: bbl-state
    - get: autoscaler-env-bbl-config
      trigger: true
    - get: app-autoscaler-ci
  - task: setup-infrastructure
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_ENV_NAME: autoscaler
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((autoscaler_deployer_key))
      BBL_GCP_PROJECT_ID: cloud-foundry-310819
      BBL_GCP_REGION: europe-west4
      BBL_GCP_ZONE: europe-west4-a
      DEBUG_MODE: true
      LB_DOMAIN: autoscaler.ci.cloudfoundry.org
      BBL_LB_CERT: ((autoscaler_lb_cert))
      BBL_LB_KEY: ((autoscaler_lb_key))
    input_mapping:
      bbl-state: bbl-state
      bbl-config: autoscaler-env-bbl-config
    ensure:
      put: bbl-state
      params:
        repository: updated-bbl-state
        rebase: true
  - task: update-dns-servers
    file: app-autoscaler-ci/autoscaler/tasks/update-dns-servers.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((autoscaler_deployer_key))
      BBL_GCP_PROJECT_ID: cloud-foundry-310819
      GCP_DNS_ZONE: ci-cloudfoundry-org
      GCP_DNS_NAME: autoscaler.ci.cloudfoundry.org



- name: delete-autoscaler
  serial_groups: [infra]
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: bbl-state
    - get: cf-deployment-concourse-tasks
  - task: delete-autoscaler
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    params:
      DEPLOYMENT_NAME: app-autoscaler
    input_mapping:
      bbl-state: bbl-state



- name: delete-cf
  serial_groups: [infra]
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: bbl-state
    - get: cf-deployment-concourse-tasks
  - task: delete-cf
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    params:
      DEPLOYMENT_NAME: cf
    input_mapping:
      bbl-state: bbl-state



- name: destroy-infrastructure
  serial_groups: [infra]
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: bbl-state
    - get: cf-deployment-concourse-tasks
  - task: destroy-infrastructure
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_IAAS: gcp
      BBL_ENV_NAME: autoscaler
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((autoscaler_deployer_key))
      BBL_GCP_PROJECT_ID: cloud-foundry-310819
    input_mapping:
      bbl-state: bbl-state
    ensure:
      put: bbl-state
      params:
        repository: updated-bbl-state
        rebase: true



- name: deploy-cf
  serial_groups: [infra]
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: cf-deployment
    - get: bbl-state
      passed: [setup-infrastructure]
      trigger: true
    - get: autoscaler-env-vars-store
  - task: deploy-cf
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      bbl-state: bbl-state
      cf-deployment: cf-deployment
      ops-files: cf-deployment
      vars-files: autoscaler-env-vars-store
    params:
      SYSTEM_DOMAIN: autoscaler.ci.cloudfoundry.org
      OPS_FILES: "operations/scale-to-one-az.yml operations/use-compiled-releases.yml"
    ensure:
      put: autoscaler-env-vars-store
      params:
        repository: autoscaler-env-vars-store
        rebase: true
  - task: smoke-tests
    file: cf-deployment-concourse-tasks/run-errand/task.yml
    input_mapping:
      bbl-state: bbl-state
    params:
      ERRAND_NAME: smoke-tests




- name: acceptance-main
  serial_groups: [infra]
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: app-autoscaler-ci
    - get: bbl-state
      passed: [deploy-cf]
    - get: app-autoscaler-release-main
      passed: [unit-tests-main, integration-tests-main]
      trigger: true
  - task: run-pre-release-script
    file: app-autoscaler-ci/autoscaler/tasks/run-prerelease-script.yml
    params:
      SCRIPT_NAME: ./scripts/update
    input_mapping:
      release: app-autoscaler-release-main
    output_mapping:
      release: app-autoscaler-release-main
  - task: deploy-autoscaler
    file: app-autoscaler-ci/autoscaler/tasks/deploy-autoscaler.yml
    params:
      SYSTEM_DOMAIN: autoscaler.ci.cloudfoundry.org
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
  - task: autoscaler-acceptance
    file: app-autoscaler-ci/autoscaler/tasks/run-acceptance-tests.yml
    params:
      SYSTEM_DOMAIN: autoscaler.ci.cloudfoundry.org
      SERVICE_OFFERING_ENABLED: true
      SKIP_SSL_VALIDATION: true
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
    ensure:
      task: cleanup
      file: app-autoscaler-ci/autoscaler/tasks/cleanup-autoscaler.yml
      params:
        SYSTEM_DOMAIN: autoscaler.ci.cloudfoundry.org
        SKIP_SSL_VALIDATION: true
      input_mapping:
        app-autoscaler-release: app-autoscaler-release-main



- name: upgrade-test-main
  serial_groups: [infra]
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: app-autoscaler-ci
    - get: bbl-state
      passed: [deploy-cf]
    - get: app-autoscaler-release-main
      passed: [acceptance-main]
      trigger: true
    - get: previous-stable-release
  - task: deploy-previous-stable-release
    file: app-autoscaler-ci/autoscaler/tasks/deploy-previous-autoscaler.yml
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
    params:
      SYSTEM_DOMAIN: autoscaler.ci.cloudfoundry.org
    on_failure:
      task: cleanup
      file: app-autoscaler-ci/autoscaler/tasks/cleanup-autoscaler.yml
      params:
        SYSTEM_DOMAIN: autoscaler.ci.cloudfoundry.org
        SKIP_SSL_VALIDATION: true
      input_mapping:
        app-autoscaler-release: app-autoscaler-release-main
  - task: run-pre-release-script
    file: app-autoscaler-ci/autoscaler/tasks/run-prerelease-script.yml
    params:
      SCRIPT_NAME: ./scripts/update
    input_mapping:
      release: app-autoscaler-release-main
    output_mapping:
      release: app-autoscaler-release-main
  - task: deploy-autoscaler
    file: app-autoscaler-ci/autoscaler/tasks/deploy-autoscaler.yml
    params:
      SYSTEM_DOMAIN: autoscaler.ci.cloudfoundry.org
      USE_POSTGRES_PERSISTENT_DISK: true
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
    on_failure:
      task: get-logs-on-failure
      file: app-autoscaler-ci/autoscaler/tasks/get-logs.yml
  - task: autoscaler-acceptance
    file: app-autoscaler-ci/autoscaler/tasks/run-acceptance-tests.yml
    params:
      SYSTEM_DOMAIN: autoscaler.ci.cloudfoundry.org
      SERVICE_OFFERING_ENABLED: true
      SKIP_SSL_VALIDATION: true
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
    ensure:
      task: cleanup
      file: app-autoscaler-ci/autoscaler/tasks/cleanup-autoscaler.yml
      params:
        SYSTEM_DOMAIN: autoscaler.ci.cloudfoundry.org
        SKIP_SSL_VALIDATION: true
      input_mapping:
        app-autoscaler-release: app-autoscaler-release-main





- name: acceptance-pr
  serial_groups: [infra]
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: app-autoscaler-ci
    - get: bbl-state
      passed: [deploy-cf]
    - get: app-autoscaler-release-pr
      passed: [unit-tests-pr, integration-tests-pr]
      trigger: true
      version: every
      params:
        submodules: true
  - put: app-autoscaler-release-pr
    params:
      path: app-autoscaler-release-pr
      status: pending
      context: acceptance-tests
    get_params:
      submodules: true
  - task: run-pre-release-script
    file: app-autoscaler-ci/autoscaler/tasks/run-prerelease-script.yml
    params:
      SCRIPT_NAME: ./scripts/update
    input_mapping:
      release: app-autoscaler-release-pr
    output_mapping:
      release: app-autoscaler-release-pr
  - task: deploy-autoscaler
    file: app-autoscaler-ci/autoscaler/tasks/deploy-autoscaler.yml
    params:
      SYSTEM_DOMAIN: autoscaler.ci.cloudfoundry.org
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-pr
  - task: autoscaler-acceptance
    file: app-autoscaler-ci/autoscaler/tasks/run-acceptance-tests.yml
    params:
      SYSTEM_DOMAIN: autoscaler.ci.cloudfoundry.org
      SERVICE_OFFERING_ENABLED: true
      SKIP_SSL_VALIDATION: true
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-pr
    ensure:
      task: cleanup
      file: app-autoscaler-ci/autoscaler/tasks/cleanup-autoscaler.yml
      params:
        SYSTEM_DOMAIN: autoscaler.ci.cloudfoundry.org
        SKIP_SSL_VALIDATION: true
      input_mapping:
        app-autoscaler-release: app-autoscaler-release-pr
  on_success:
    put: app-autoscaler-release-pr
    params:
      path: app-autoscaler-release-pr
      status: success
      context: acceptance-tests
  on_failure:
    put: app-autoscaler-release-pr
    params:
      path: app-autoscaler-release-pr
      status: failure
      context: acceptance-tests




- name: release
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: release
    - get: gh-release
    - get: app-autoscaler-ci
    - get: app-autoscaler-release-main
      passed: [upgrade-test-main]
  - task: run-pre-release-script
    file: app-autoscaler-ci/autoscaler/tasks/run-prerelease-script.yml
    params:
      SCRIPT_NAME: ./scripts/update
    input_mapping:
      release: app-autoscaler-release-main
    output_mapping:
      release: app-autoscaler-release-main
  - task: release-autoscaler
    file: app-autoscaler-ci/autoscaler/tasks/release-autoscaler.yml
    params:
      UPLOADER_KEY: ((autoscaler_blobstore_uploader_key))
      GITHUB_TOKEN: ((autoscaler_access_token))
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
  - put: app-autoscaler-release-main
    params:
      rebase: true
      repository: pushme/app-autoscaler-release
  - put: release
    params:
      file: "generated-release/artifacts/app-autoscaler-*.tgz"
  - put: gh-release
    params:
      name: generated-release/name
      tag: generated-release/tag
      body: generated-release/changelog.md
      globs: [generated-release/artifacts/*]




- name: draft-pr
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: gh-release
    - get: app-autoscaler-ci
    - get: app-autoscaler-release-pr
      passed: [acceptance-pr]
      trigger: true
  - task: dummy-release-autoscaler
    file: app-autoscaler-ci/autoscaler/tasks/release-autoscaler.yml
    params:
      UPLOADER_KEY: ((autoscaler_blobstore_uploader_key))
      GITHUB_TOKEN: ((autoscaler_access_token))
      PERFORM_BOSH_RELEASE: false
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-pr




- name: draft
  public: true
  build_logs_to_retain: 100
  plan:
  - in_parallel:
    - get: gh-release
    - get: app-autoscaler-ci
    - get: app-autoscaler-release-main
      passed: [upgrade-test-main]
      trigger: true
  - task: dummy-release-autoscaler
    file: app-autoscaler-ci/autoscaler/tasks/release-autoscaler.yml
    params:
      UPLOADER_KEY: ((autoscaler_blobstore_uploader_key))
      GITHUB_TOKEN: ((autoscaler_access_token))
      PERFORM_BOSH_RELEASE: false
    input_mapping:
      app-autoscaler-release: app-autoscaler-release-main
