#@ load("@ytt:template", "template")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:library", "library")
#@ load("@ytt:overlay", "overlay")

#@ def credhub_values():
key_store_password: $(.credhub-keystore-key.data.password)
trust_store_password: $(.credhub-truststore-key.data.password)
encryption_password: $(.credhub-encryption-key.data.password)
use_local_image: false
uaa_url: http://uaa.concourse.svc.cluster.local:8080

database:
  scheme: postgres
  username: credhub
  password: $(.credhub-postgresql-password.data.password)
  address: "REPLACEME"
  port: 5432
  name: credhub
#@ end

#@ credhub = library.get("credhub")

#@ credhub_with_vals = credhub.with_data_values(credhub_values())
#@ credhub_config = credhub_with_vals.export("config")

#@ def credhub_config_updates():
security:
  authorization:
    acls:
      #@overlay/replace
      enabled: false
    #@overlay/replace
    permissions:
      - actors:
          - "uaa-client:credhub_cli"
          - "uaa-client:credhub_admin_client"
        operations:
          - read
          - write
          - delete
          - read_acl
          - write_acl
        path: "/*"
#@ end

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: credhub-config
  namespace: concourse
spec:
  inputResources:
  - name: credhub-postgresql-password
    ref:
      apiVersion: v1
      kind: Secret
      name: credhub-postgresql-password
  - name: credhub-keystore-key
    ref:
      apiVersion: v1
      kind: Secret
      name: credhub-keystore-key
  - name: credhub-truststore-key
    ref:
      apiVersion: v1
      kind: Secret
      name: credhub-truststore-key
  - name: credhub-encryption-key
    ref:
      apiVersion: v1
      kind: Secret
      name: credhub-encryption-key
  template:
    stringData:
      application.yml: #@ yaml.encode(overlay.apply(credhub_config()[0], credhub_config_updates()))

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: credhub-keystore-key
  namespace: concourse

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: credhub-truststore-key
  namespace: concourse

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: credhub-encryption-key
  namespace: concourse

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Certificate
metadata:
  namespace: concourse
  name: credhub-root-ca
spec:
  isCA: true
  secretTemplate:
    stringData:
      certificate: $(certificate)
      private_key: $(privateKey)