// Code generated by ogen, DO NOT EDIT.

package api

// V1AppsGUIDPolicyDeleteParams is parameters of DELETE /v1/apps/{guid}/policy operation.
type V1AppsGUIDPolicyDeleteParams struct {
	// The GUID identifying the application for which the scaling history is fetched.
	// It can be found in the `application_id` property of the JSON object stored in the
	// `VCAP_APPLICATION` environment variable.
	GUID string
}

// V1AppsGUIDPolicyGetParams is parameters of GET /v1/apps/{guid}/policy operation.
type V1AppsGUIDPolicyGetParams struct {
	// The GUID identifying the application for which the scaling history is fetched.
	// It can be found in the `application_id` property of the JSON object stored in the
	// `VCAP_APPLICATION` environment variable.
	GUID string
}

// V1AppsGUIDPolicyPutParams is parameters of PUT /v1/apps/{guid}/policy operation.
type V1AppsGUIDPolicyPutParams struct {
	// The GUID identifying the application for which the scaling history is fetched.
	// It can be found in the `application_id` property of the JSON object stored in the
	// `VCAP_APPLICATION` environment variable.
	GUID string
}
