#!/bin/bash

set -x -e

RUN_DIR=/var/vcap/sys/run/scalingengine
LOG_DIR=/var/vcap/sys/log/scalingengine
CONF_DIR=/var/vcap/jobs/scalingengine/config
PIDFILE=$RUN_DIR/scalingengine.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "scalingengine"

    mkdir -p $RUN_DIR
    chown -R vcap:vcap $RUN_DIR
    mkdir -p $LOG_DIR
    chown -R vcap:vcap $LOG_DIR

    echo $$ > $PIDFILE
    
    exec /var/vcap/packages/scalingengine/scalingengine -c $CONF_DIR/scalingengine.yml >>$LOG_DIR/scalingengine.stdout.log 2>>$LOG_DIR/scalingengine.stderr.log
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  *)
  echo "Usage: scalingengine_ctl {start|stop}" ;;
esac
exit 0