---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-deploy
    tag: main

run:
  path: app-autoscaler-release-main/ci/autoscaler/scripts/check-diego-cell-count.sh
