---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-tools
    tag: main

inputs:
- name: bbl-state
- name: app-autoscaler-release

params:
  EXPECTED_CELLS:

run:
  path: app-autoscaler-release/ci/autoscaler/scripts/check-diego-cell-count.sh
