---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-tools
    tag: main

params:
  SYSTEM_DOMAIN:
  SKIP_SSL_VALIDATION: false
  AUTOSCALER_DIR: app-autoscaler-release

inputs:
- name: app-autoscaler-release
- name: ci
- name: bbl-state

outputs:

run:
  path: ci/ci/autoscaler/scripts/register-broker.sh
