---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-test
    tag: main

params:
  SCRIPT_NAME:

inputs:
- name: release

outputs:
- name: release  

run:
  path: release/ci/autoscaler/scripts/run-prerelease-script.sh
