---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-test
    tag: main
inputs:
- name: app-autoscaler-release

run:
  path: app-autoscaler-release/ci/autoscaler/scripts/run-integration-tests.sh
