openapi: 3.0.0
info: 
  title: Policy API
  description: This API is used to create, delete, retrieve the policy
  version: 1.0.0
  security: 
- mtls: []
- basicAuthentication: []
tags:
- name: Policy API V1
  description: This API is used to create, delete, retrieve the policy

paths: 
  /v1/apps/{guid}/policy:
    parameters:
    - name: guid
      in: path
      required: true
      description: |

        The GUID identifying the application for which the scaling history is fetched.

        It can be found in the `application_id` property of the JSON object stored in the
        `VCAP_APPLICATION` environment variable.
      schema:
        $ref: "./shared_definitions.yaml#/schemas/GUID"
    
    - name: Authorization
      in: header
      schema: 
        type: string
        example: |
          bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoidWFhLWlkLTQwOCIsImVtYWlsIjoiZW1haWwtMzAzQHNvbWVkb21haW4uY29tIiwic2NvcGUiOlsiY2xvdWRfY29udHJvbGxlci5hZG1pbiJdLCJhdWQiOlsiY2xvdWRfY29udHJvbGxlciJdLCJleHAiOjE0NDU1NTc5NzF9.RMJZvSzCSxpj4jjZBmzbO7eoSfTAcIWVSHqFu5_Iu_o
    put:
      summary: Retrieves the Policy 
      description: This API is used to create the policy
      tags:
      - Create Policy API V1
      response: 
        "200":
          description: "OK"
          content:
           application/json:
            schema:
              $ref: "#/components/schemas/Policy/CreatePolicy"
        default: 
          $ref: "./shared_definitons.yaml#/responses/Error" 
components:
  schemas:
    CreatePolicy:
      description: Object creating Policy 
      type: object
      properties:
        instance_min_count:
          type: integer
          format: int64
          description: minimal number of instance count
          example: 1
        instance_max_count: 
          type: integer
          format: int64
          description: maximal number of instance count
          example: 4
        scaling_rules:
          type: array
          items:
            $ref: '#/components/schemas/ScalingRule'
    ScalingRule:
      properties:
        metric_type:
          - $ref: "./shared_definitions.yaml#/schemas/metric_type"
        threshold:
          description: |
            The boundary when metric value exceeds is considered as a breach
          required: true
          type: int
          format: int64
          example: 30
        operator:
          description: Used for standard operting signs - ">", "<", ">=", "<="
          required: true
          type: string
          enum: [">", "<", ">=", "<="]
          example: <
        adjustment:
          description: |
            The adjustment approach for instance count with each scaling.

            +5 means adding 5 instances, -50% means shrinking to the half of current size.
          required: true
          type: string
          pattern: ^[-+][1-9]+[0-9]*[%]?$
          example: -1
        breach_duration_secs:
          description: |
            Time duration(in seconds) to fire scaling event if it keeps breaching
          type: integer
          format: int64  # this is time in seconds
          example: 600
        cool_down_secs:
          description: |
            The time duration (in seconds) to wait before the next scaling kicks in
          type: integer
          format: int64  # this is time in seconds
          example: 300
        schedules:
          type: array
          items:
            $ref: '#/components/schemas/Schedules'
    Schedules:
      timezone:
        description: Using timezone definition of Java #https://docs.oracle.com/javase/8/docs/api/java/util/TimeZone.html - Do we need to implement it?
        required: true
        type: string
        example: Asia/Shanghai
        # TODO: Try to make use of <https://stackoverflow.com/a/71121905>
        #- $ref: "../../src/autoscaler/api/policyvalidator/policy_json.schema.json#/" # TODO:
      recurring_schedule:
        - $ref: "./shared_definitions.yaml#/schemas/recurring_schedule"
      specific_date:
        - $ref: "./shared_definitions.yaml#/schemas/specific_date"
    delete:
      summary: Deletes the policy 
      description: This API is used to delete the policy
      tags: 
      - Delete Policy API V1
      response: 
        "200":
          description: "OK"
          content:
           application/json:
            schema:
              $ref: "#/components/schemas/Policy/DeletePolicy"
        default: 
          $ref: "./shared_definitons.yaml#/responses/Error"
    get:
      summary: Retrieves the Policy 
      description: This API is used to retrieve the policy
      tags:
      - Get Policy API V1
      response: 
        "200":
          description: "OK"
          content:
           application/json:
            schema:
              $ref: "#/components/schemas/Policy/GetPolicy"
        default: 
          $ref: "./shared_definitons.yaml#/responses/Error"
components:
  schemas:
    GetPolicy:
      description: Object containing Policy 
      type: object
      properties:
        instance_min_count:
          type: integer
          format: int64
          description: minimal number of instance count
          example: 2
        instance_max_count: 
          type: integer
          format: int64
          description: maximal number of instance count
          example: 4
        scaling_rules:
          type: array
          items:
            $ref: '#/components/schemas/ScalingRules'
    ScalingRules:
      metric_type:
        - $ref: "./shared_definitions.yaml#/schemas/metric_type"
      threshold:
        - $ref: "./shared_definitions.yaml#/schemas/threshold"
      operator:
        - $ref: "./shared_definitions.yaml#/schemas/operator"
      adjustment:
        - $ref: "./shared_definitions.yaml#/schemas/adjustment"
      breach_duration_secs:
        - $ref: "./shared_definitions.yaml#/schemas/breach_duration_secs"
      cool_down_secs:
        - $ref: "./shared_definitions.yaml#/schemas/cool_down_secs"
        schedules:
          type: array
          items:
            $ref: '#/components/schemas/Schedules'
    Schedules:
      timezone:
        - $ref: "./shared_definitions.yaml#/schemas/timezone"
      recurring_schedule:
        - $ref: "./shared_definitions.yaml#/schemas/recurring_schedule"
      specific_date:
        - $ref: "./shared_definitions.yaml#/schemas/specific_date"