name: Acceptance Tests Cleanup (Buildin)
on:
  pull_request:
    types: [ closed ]
    paths:
      - 'src/acceptance/**'

env:
  MAVEN_VERSION: 3.6.3
  MAVEN_SHA: c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
  BUILDIN_MODE: true
  SERVICE_OFFERING_ENABLED: false
  check_name: "acceptance_test_check_broker"
  PR_NUMBER: "${{ github.event.pull_request.number }}"
  DEPLOYMENT_NAME: "autoscaler-${{ github.event.pull_request.number }}"
  SERVICE_BROKER_NAME: "autoscaler-${{ github.event.pull_request.number }}servicebroker"
  SERVICE_NAME: "autoscaler-${{ github.event.pull_request.number }}"
  BBL_STATE_PATH: "${{ github.workspace }}/bbl/bbl-state"
  NAME_PREFIX: "autoscaler-${{ github.event.pull_request.number }}-TESTS"
  AUTOSCALER_DIR: "${{ github.workspace }}/app-autoscaler-release"
  CI_DIR: "${{ github.workspace }}/app-autoscaler-release/ci"

jobs:
  deployment_cleanup:
    name: Cleanup deployments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: app-autoscaler-release
          ref: main
      - uses: ./app-autoscaler-release/.github/actions/acceptance_tests_common
        with:
          ssh-key: ${{ secrets.BBL_SSH_KEY }}

      - run: |
          cd ${{ env.AUTOSCALER_DIR }}
          make deployment-cleanup
