name: Acceptance Tests Cleanup (Buildin)
on:
  pull_request:
    types: [labeled, synchronize, closed] # [closed]
    paths:
      - ".github/workflows/acceptance_tests_buildin.yaml"
      - ".github/workflows/acceptance_tests_buildin_close.yaml"
      - "Makefile"
      - "src/acceptance/**"

env:
  BUILDIN_MODE: true
  SERVICE_OFFERING_ENABLED: false
  PR_NUMBER: "${{ github.event.pull_request.number }}"
  DEPLOYMENT_NAME: "autoscaler-buildin-${{ github.event.pull_request.number }}"
  BBL_STATE_PATH: "${{ github.workspace }}/bbl/bbl-state"
  AUTOSCALER_DIR: "${{ github.workspace }}/app-autoscaler-release"
  CI_DIR: "${{ github.workspace }}/app-autoscaler-release/ci"

jobs:
  deployment_cleanup:
    name: Cleanup deployments
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cloudfoundry/app-autoscaler-release-tools:main
    steps:
      - uses: actions/checkout@v4
        with:
          path: app-autoscaler-release
          ref: main

      - uses: ./app-autoscaler-release/.github/actions/setup-environment
        with:
          ssh-key: ${{ secrets.BBL_SSH_KEY }}

      - name: "clean up"
        shell: bash
        run: |
          #! /usr/bin/env bash
          set -eu -o pipefail

          # The subsequent assignment is needed by the checkout-action to behave properly!
          # See: <https://github.com/actions/checkout/issues/785>
          GITHUB_WORKSPACE='${{ github.workspace }}'

          echo "GITHUB_WORKSPACE = ${GITHUB_WORKSPACE}"
          echo "github.workspace = ${{ github.workspace }}"
          echo "pwd := $(pwd)"
          ls -lah . # TODO: Debug
          ls -lah '${{ github.workspace }}' # TODO: Debug

          make --directory="${AUTOSCALER_DIR}" deploy-cleanup
