name: Acceptance Tests
#on:
#  push:
env:
  MAVEN_VERSION: 3.6.3
  MAVEN_SHA: c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
  BUILTIN: true
  DEPLOYMENT_NAME: "app-autoscaler-${{ github.event.pull_request.number }}"
  SERVICE_BROKER_NAME: "app-autoscaler-${{ github.event.pull_request.number }}servicebroker"
  SERVICE_NAME: "autoscaler-${{ github.event.pull_request.number }}"
  BBL_STATE_PATH: "${{ github.workspace }}/bbl/bbl-state"
  SYSTEM_DOMAIN: "autoscaler.ci.cloudfoundry.org"
  SERVICE_OFFERING_ENABLED: false
  SKIP_SSL_VALIDATION: true
  NAME_PREFIX: "app-autoscaler-${{ github.event.pull_request.number }}-TESTS"
  NODES: 3
  AUTOSCALER_DIR: "${{ github.workspace }}/app-autoscaler-release"
  CI_DIR: "${{ github.workspace }}/app-autoscaler-release/ci"
  check_name: "acceptance_test_check"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy_autoscaler:
    name: "Deploy for acceptance tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: app-autoscaler-release
      - uses: ./app-autoscaler-release/.github/actions/acceptance_tests_common
        with:
          ssh-key: ${{ secrets.BBL_SSH_KEY }}

      # TODO: When removing metricserver and metricgateway merge enable-log-cache.yml into the default templates/app-autoscaler.yml manifest.
      - name: deploy autoscaler
        run: |
          cd ${{ env.AUTOSCALER_DIR }}
          echo ${{ env.BBL_STATE_PATH }}
          make deploy DEPLOYMENT_NAME=${{ env.DEPLOYMENT_NAME }} BBL_STATE_PATH=${{ env.BBL_STATE_PATH }}

  acceptance_test_api:
    needs: [ deploy_autoscaler ]
    name: "API acceptance tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: app-autoscaler-release
      - uses: ./app-autoscaler-release/.github/actions/acceptance_tests_common
        with:
          ssh-key: ${{ secrets.BBL_SSH_KEY }}

      - name: run acceptance test - api
        run: |
          export SUITES="api"
          ${CI_DIR}/autoscaler/scripts/run-acceptance-tests.sh

  acceptance_test_app:
    needs: [ deploy_autoscaler ]
    name: "APP acceptance tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: app-autoscaler-release
      - uses: ./app-autoscaler-release/.github/actions/acceptance_tests_common
        with:
          ssh-key: ${{ secrets.BBL_SSH_KEY }}

      - name: run acceptance test - app
        run: |
          export SUITES="app"
          ${CI_DIR}/autoscaler/scripts/run-acceptance-tests.sh
