name: Acceptance Tests - MTA
on:
  pull_request:
    types: [ opened, synchronize ]

concurrency:
  group: "${{ github.workflow }}/${{ github.ref }}"
  cancel-in-progress: true

jobs:
  acceptance_tests_reusable:
    name: "${{ github.workflow }}"
    uses: ./.github/workflows/acceptance_tests_reusable.yaml
    with:
      deployment_name: "autoscaler-mta-${{ github.event.pull_request.number }}"
      deploy_apps: true
      ops_files: |
        operations/add-releases.yml
        operations/instance-identity-cert-from-cf.yml
        operations/add-postgres-variables.yml
        operations/enable-nats-tls.yml
        operations/add-extra-plan.yml
        operations/set-release-version.yml
        operations/enable-metricsforwarder-via-syslog-agent.yml
        operations/enable-scheduler-logging.yml
        operations/use-cf-services.yml
    secrets:
      bbl_ssh_key: "${{ secrets.BBL_SSH_KEY }}"
