name: Acceptance Tests Cleanup (Buildin)
on:
  pull_request:
    types: [closed]
    paths:
      - "Makefile"
      - "src/acceptance/**"

env:
  BUILDIN_MODE: true
  SERVICE_OFFERING_ENABLED: false
  PR_NUMBER: "${{ github.event.pull_request.number }}"
  DEPLOYMENT_NAME: "autoscaler-buildin-${{ github.event.pull_request.number }}"

jobs:
  deployment_cleanup:
    name: Cleanup deployments
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cloudfoundry/app-autoscaler-release-tools:main
    steps:
      - uses: actions/checkout@v4
        with:
          path: app-autoscaler-release
          ref: main

      - uses: ./app-autoscaler-release/.github/actions/setup-environment
        with:
          ssh-key: ${{ secrets.BBL_SSH_KEY }}

      - name: "clean up"
        shell: bash
        run: |
          #! /usr/bin/env bash
          set -eu -o pipefail

          # The subsequent assignments are needed *HERE* because of:
          # <https://github.com/actions/runner/issues/2058> or
          # <https://github.com/actions/checkout/issues/785>
          export BBL_STATE_PATH="${GITHUB_WORKSPACE}/bbl/bbl-state"
          declare -r AUTOSCALER_DIR="${GITHUB_WORKSPACE}/app-autoscaler-release"

          make --directory="${AUTOSCALER_DIR}" deploy-cleanup
