name: Dependency spec updates
on: pull_request

jobs:
  package-specs:
    runs-on: ubuntu-latest
    if: contains(fromJson('["dependabot[bot]", "renovate[bot]"]'), github.event.pull_request.user.login) && contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go

      - name: package-specs
        run: |
          make package-specs
      - name: Check if there are changes
        id: changes
        run: echo "changed=$(git status --porcelain | wc -l)" >> $GITHUB_ENV
      - name: Process changes
        if: steps.changes.outputs.changed != 0
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: './packages/**/spec'
          message: 'Updating spec files from `dependabot[bot]` changes'
          push: true


