name: Notify of incomming or re-opened PR's
on:
  pull_request:
    types: [opened, reopened]
jobs:
  pr-notify:
    name: send a notification of a Open or re-opened PR
    runs-on: ubuntu-latest
    steps:
      - name: notify slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.