name: Notify of incomming or re-opened PR's
on:
  pull_request:
#    types: [opened, reopened]
    - opened
    - labeled
    - unlabeled
jobs:
  pr-notify:
    name: send a notification of a Open or re-opened PR
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          none_of: WIP,wip,Do Not Merge,draft
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: notify slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          icon_emoji: ':gh-pull-request:'
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
          custom_payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*New PR in Application autoscaler*\n\n - *Author*: ${process.env.AS_AUTHOR}\n - *PR*: ${process.env.AS_PULL_REQUEST}"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "https://samlearnsazure.files.wordpress.com/2020/02/00featuredimage-4.png?w=200&h=200&crop=1",
                    "alt_text": "Pull request"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Add your review :green:",
                        "emoji": true
                      },
                      "value": "add your review",
                      "url": "${context.payload.pull_request?.html_url}/files#submit-review"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required