name: "Validate OpenAPI-Specifications"
on:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cloudfoundry/app-autoscaler-release-tools:main@sha256:131616bf21483c9a519d32dfea14b8424b092ff6b93060f7928eaac3cfa01fff
    steps:
    - name: Get Repository content
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Validating OpenAPI Specifications
      shell: bash
      run: |
        #! /usr/bin/env bash

        set -eu -o pipefail
        make validate-openapi-specs