name: "Validate OpenAPI-Specifications"
on:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cloudfoundry/app-autoscaler-release-tools:main@sha256:b89f25eeea092104fb75e8e7eaf76b0dbd3156bec51ea234670ff0bdd1fc6e8b
    steps:
    - name: Get Repository content
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Validating OpenAPI Specifications
      shell: bash
      run: |
        #! /usr/bin/env bash

        set -eu -o pipefail
        make validate-openapi-specs