name: "Validate OpenAPI-Specifications"
on:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Get Repository content
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    - name: Install devbox
      uses: jetify-com/devbox-install-action@22b0f5500b14df4ea357ce673fbd4ced940ed6a1 # v0.13.0
      with:
        enable-cache: 'true'
    - name: Make devbox shellenv available
      run: |
        eval "$(devbox shellenv)"
        printenv >> "$GITHUB_ENV"
    - name: Validating OpenAPI Specifications
      shell: bash
      run: |
        #! /usr/bin/env bash

        set -eu -o pipefail
        make validate-openapi-specs
