---
name: postgres

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  postgres:
    strategy:
      matrix:
        postgres: [9.6, 12]
    env:
      DB_DATABASE: autoscaler
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    runs-on: ubuntu-latest
    name: Build postgres=${{ matrix.postgres }}
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: autoscaler
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
  
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          submodules: true  

      - name: Determine Go Version
        id: go
        run: |
          GO_VERSION=$(cat packages/golang/spec | grep linux | sed 's/.linux-amd64.tar.gz//' | sed 's/- golang\/go//' | xargs)
          echo "::set-output name=version::${GO_VERSION}"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go.outputs.version }}
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      
      - name: Maven Build
        run: |
          pushd src/app-autoscaler
            mvn --no-transfer-progress package -Dmaven.test.skip=true
          popd

      - name: Setup Postgres
        run: |
          pushd src/app-autoscaler
            java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:postgresql://127.0.0.1/autoscaler --driver=org.postgresql.Driver --changeLogFile=src/autoscaler/api/db/api.db.changelog.yml --username=${{ env.POSTGRES_USER }} --password=${{ env.POSTGRES_PASSWORD }} update
            java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:postgresql://127.0.0.1/autoscaler --driver=org.postgresql.Driver --changeLogFile=src/autoscaler/servicebroker/db/servicebroker.db.changelog.json --username=${{ env.POSTGRES_USER }} --password=${{ env.POSTGRES_PASSWORD }} update
            java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:postgresql://127.0.0.1/autoscaler --driver=org.postgresql.Driver --changeLogFile=scheduler/db/scheduler.changelog-master.yaml --username=${{ env.POSTGRES_USER }} --password=${{ env.POSTGRES_PASSWORD }} update
            java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:postgresql://127.0.0.1/autoscaler --driver=org.postgresql.Driver --changeLogFile=scheduler/db/quartz.changelog-master.yaml --username=${{ env.POSTGRES_USER }} --password=${{ env.POSTGRES_PASSWORD }} update
            java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:postgresql://127.0.0.1/autoscaler --driver=org.postgresql.Driver --changeLogFile=src/autoscaler/metricsserver/db/metricscollector.db.changelog.yml --username=${{ env.POSTGRES_USER }} --password=${{ env.POSTGRES_PASSWORD }} update
            java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:postgresql://127.0.0.1/autoscaler --driver=org.postgresql.Driver --changeLogFile=src/autoscaler/eventgenerator/db/dataaggregator.db.changelog.yml --username=${{ env.POSTGRES_USER }} --password=${{ env.POSTGRES_PASSWORD }} update
            java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:postgresql://127.0.0.1/autoscaler --driver=org.postgresql.Driver --changeLogFile=src/autoscaler/scalingengine/db/scalingengine.db.changelog.yml --username=${{ env.POSTGRES_USER }} --password=${{ env.POSTGRES_PASSWORD }} update
            java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:postgresql://127.0.0.1/autoscaler --driver=org.postgresql.Driver --changeLogFile=src/autoscaler/operator/db/operator.db.changelog.yml --username=${{ env.POSTGRES_USER }} --password=${{ env.POSTGRES_PASSWORD }} update
          popd

      - name: Unit Test
        run: |
          pushd src/changeloglockcleaner
            go get github.com/onsi/ginkgo/ginkgo
            export DBURL="postgres://postgres:postgres@localhost/autoscaler?sslmode=disable"
            ginkgo -r -race -randomizeAllSpecs -keepGoing
          popd
