#TODO:  Unexpected error running Liquibase: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:postgresql://127.0.0.1/autoscaler with driver org.postgresql.Driver.  Connection to 127.0.0.1:5432 refused. 
# https://github.com/cloudfoundry/app-autoscaler-release/actions/runs/3549168357/jobs/5961226050#step:8:40
---
name: ARC - Build with Postgres

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}/${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        postgres: [9.6, 12]
        suite: [test, integration]
    env:
      DB_DATABASE: autoscaler
      DB_USER: postgres
      DB_PASSWORD: postgres
      MAVEN_VERSION: 3.6.3
      MAVEN_SHA: c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
  container-job:
    runs-on: self-hosted
    container:
      image: booker/app-autoscaler-release-tools
    continue-on-error: true
    name: Build suite=${{ matrix.suite }}, jdk=${{ matrix.java }}, postgres=${{ matrix.postgres }}
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: autoscaler
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Build
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
        run: |
          make build
      - name: ${{ matrix.suite }}
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: autoscaler
        run: |
          make ${{ matrix.suite }}
