---
name: Build with Postgres

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}/${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        postgres: [15, 16]
        suite: [test, integration]
    env:
      DB_DATABASE: autoscaler
      DB_USER: postgres
      DB_PASSWORD: postgres
    runs-on: "ubuntu-latest"
    container:
      image: "ubuntu:noble@sha256:353675e2a41babd526e2b837d7ec780c2a05bca0164f7ea5dbbd433d21d166fc"
    continue-on-error: true
    name: Build suite=${{ matrix.suite }}, postgres=${{ matrix.postgres }}
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: autoscaler
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
         - 5432:5432
    steps:
      - name: Install devbox-prerequisites
        shell: bash
        run: |
          set -eu -o pipefail
          apt-get update
          apt-get install --assume-yes gh git curl

      - name: Trust my checkout
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install devbox
        uses: jetify-com/devbox-install-action@22b0f5500b14df4ea357ce673fbd4ced940ed6a1 # v0.13.0
        env:
          ACT: true # This causes devbox to do a non-multiuser Nix-installation
          DEVBOX_DEBUG: 1

      - name: make generate-openapi-generated-clients-and-servers
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
        run: |
          devbox run make generate-openapi-generated-clients-and-servers

      - name: make ${{ matrix.suite }}
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: autoscaler
        run: |
          devbox run make ${{ matrix.suite }} DB_HOST="${POSTGRES_HOST}"
