---
name: Build with Postgres

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}/${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        postgres: [12, 15, 16]
        suite: [test, integration]
    env:
      DB_DATABASE: autoscaler
      DB_USER: postgres
      DB_PASSWORD: postgres
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cloudfoundry/app-autoscaler-release-tools:main@sha256:edd58762b4e2447676f1ccd30ba9d03f358548b2e047f277ff693d19f6fefb90
    continue-on-error: true
    name: Build suite=${{ matrix.suite }}, postgres=${{ matrix.postgres }}
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: autoscaler
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
         - 5432:5432
    steps:
      - name: Trust my checkout
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: make build
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
        run: |
          make generate-openapi-generated-clients-and-servers
          make build

      - name: make ${{ matrix.suite }}
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: autoscaler
        run: |
          make ${{ matrix.suite }} DB_HOST="${POSTGRES_HOST}"
