---
name: Build with Postgres

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java: [11, 17]
        postgres: [9.6, 12]
        suite: [test, integration]

    env:
      DB_DATABASE: autoscaler
      DB_USER: postgres
      DB_PASSWORD: postgres
      MAVEN_VERSION: 3.6.3
      MAVEN_SHA: c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
    runs-on: ubuntu-latest
    name: Build suite=${{ matrix.suite }}, jdk=${{ matrix.java }}, postgres=${{ matrix.postgres }}
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: autoscaler
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_go
      - uses: ./.github/actions/setup_java
        with:
          version: ${{ matrix.java }}

      - name: Build
        run: |
          make build

      - name: ${{ matrix.suite }}
        run: |
          make ${{ matrix.suite }}

      - name: Change Log Lock Cleaner
        run: |
          pushd src/changeloglockcleaner
            go get github.com/onsi/ginkgo/v2/ginkgo
            export DBURL="postgres://postgres:postgres@localhost/autoscaler?sslmode=disable"
            ginkgo -r --race --randomize-all --keep-going
          popd
