name: Renovate Config validation
permissions:
  contents: read
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - main
    paths:
      - .github/workflows/renovate_config_validation.yaml
      - renovate.json

jobs:
  renovate-config-validation:
    runs-on: ubuntu-latest
    name: Validate the Renovate configuration
    steps:
      - name: Validate the Renovate JSON
        run: |
          set -euxo pipefail
          npx --yes --package renovate -- renovate-config-validator
