name: Resume CI VMs

on:
  schedule:
    - cron: '0 5 * * 1-5'  # 05:00 UTC / 06:00 CET / 07:00 CEST, Monday to Friday
  workflow_dispatch:

jobs:
  resume:
    env:
      BBL_STATE_PATH: ${{ github.workspace }}/app-autoscaler-env-bbl-state/bbl-state
    runs-on: ubuntu-latest
    steps:
      - name: checkout app-autoscaler-release
        uses: actions/checkout@v4

      - name: install devbox
        uses: jetify-com/devbox-install-action@734088efddca47cf44ff8a09289c6d0e51b73218 # v0.12.0
        with:
          enable-cache: true

      - name: make devbox shellenv available
        run: |
          eval "$(devbox shellenv)"
          printenv >> "$GITHUB_ENV"

      - name: checkout app-autoscaler-env-bbl-state
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: cloudfoundry/app-autoscaler-env-bbl-state
          ssh-key: ${{ secrets.bbl_ssh_key }}
          path: app-autoscaler-env-bbl-state

      - name: test bosh command
        run: |
          direnv reload .
          bosh vms -d cf

#
#      - name: auth gcloud
#        uses: google-github-actions/auth@v2
#        with:
#          credentials_json: '${{ secrets.GCP_APP_RUNTIME_INTERFACES_AUTOSCALER_DEPLOYER_KEY }}'
#
#      - name: set up gcloud
#        uses: google-github-actions/setup-gcloud@v2
#
#      - name: resume VMs
#        run: |
#          gcloud compute instances list --filter="networkInterfaces.network:autoscaler-network" --format="value(name,zone)" --sort-by="~labels.deployment:bosh" | while read -r INSTANCE_NAME ZONE; do
#            if ! gcloud compute instances resume "$INSTANCE_NAME" --zone="$ZONE" --async; then
#              echo "failed to initiate resuming $INSTANCE_NAME in $ZONE, continuing with next instance"
#              continue
#            fi
#          done
