name: Resume CI VMs

on:
  schedule:
    - cron: '0 5 * * *'  # 05:00 UTC / 06:00 CET / 07:00 CEST
  workflow_dispatch:

jobs:
  resume:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: auth gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_APP_RUNTIME_INTERFACES_AUTOSCALER_DEPLOYER_KEY }}'

      - name: set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: resume VMs
        run: |
          gcloud compute instances list --filter="labels.belongs-to:autoscaler" --format="value(name,zone)" | while read -r INSTANCE_NAME ZONE; do
            if ! gcloud compute instances resume "$INSTANCE_NAME" --zone="$ZONE"; then
              echo "failed to resuming $INSTANCE_NAME in $ZONE, continuing with next instance"
              continue
            fi
          done
