name: Suspend CI VMs

on:
  schedule:
    - cron: '0 17 * * 1-5'  # 17:00 UTC / 18:00 CET / 19:00 CEST, Monday to Friday
  workflow_dispatch:

jobs:
  suspend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: auth gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_APP_RUNTIME_INTERFACES_AUTOSCALER_DEPLOYER_KEY }}'

      - name: set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: suspend VMs
        run: |
          gcloud compute instances list --filter="labels.belongs-to:autoscaler" --format="value(name,zone)" | while read -r INSTANCE_NAME ZONE; do
            if ! gcloud compute instances suspend "$INSTANCE_NAME" --zone="$ZONE"; then
              echo "failed to suspend $INSTANCE_NAME in $ZONE, continuing with next instance"
              continue
            fi
          done
