name: Suspend CI VMs

on:
  schedule:
    - cron: '0 17 * * *'  # 17:00 UTC / 18:00 CET / 19:00 CEST
  workflow_dispatch:

jobs:
  suspend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          credentials_json: ${{ secrets.GCP_APP_RUNTIME_INTERFACES_AUTOSCALER_DEPLOYER_KEY }}

      - name: suspend VMs
        run: |
          gcloud compute instances list --filter="labels.belongs-to:autoscaler" --format="value(name,zone)" | while read -r INSTANCE_NAME ZONE; do
            echo "suspending instance: $INSTANCE_NAME (zone: $ZONE)"
            gcloud compute instances suspend "$INSTANCE_NAME" --zone="$ZONE"
          done
